### ISSUE TITLE
Multiple Page Form

### ISSUE THREAD

**Issue by RyanPWalker** [bluebill1049/react-hook-form#100]
There doesn't seem to be a simple way to create a multiple page form.  I'm trying to save each page's form data to redux before moving on to the next page as a work around, but there isn't a good way to do that either.

Any suggestions for simple approaches I'm unaware of?  Or maybe it could be a new feature?
Thanks

**Comment by testarossaaaaa** [comment]
It's related to all react form libraries, fields are registered only if they are presented in React Virtual DOM, it's the right approach. If you want to build a wizard just render all pages at once with `visibility: hidden` and set `visibility: visual` for an active page/tab.

**Comment by RyanPWalker** [comment]
@testarossaaaaa I thought about that too, but hiding elements in the DOM is kind of a hacky fix.  Also I'm trying to add this to an existing form and I'd have to rewrite the structure to do that

**Comment by bluebill1049** [comment]
multiple page form probably should always be tied together with a state management tool. Things like redux or my simple version: https://github.com/bluebill1049/little-state-machine

**Comment by RyanPWalker** [comment]
That's what I was thinking, just wanted to make sure.  Would you recommend using `getValues()` and then saving it to the state when moving between pages?

My other problem is that my form transitions are controlled by a different child component so I'd have to pass `getValues` through the `FormContext` api but as you saw [in my other issue](https://github.com/bluebill1049/react-hook-form/issues/101), `FormContext` isn't working for me.  But that's a different subject.

**Comment by bluebill1049** [comment]
no, I wouldn't recommend using` getValues()`, I will do that at `onSubmit` because then the validation has run through and data is clean.

**Comment by RyanPWalker** [comment]
So each form page has it's own submit with `onSubmit` that validates then saves the page data to the store, and then the final submit just pulls from the `store` the complete application?

**Comment by bluebill1049** [comment]
Perfect 👌🏻
