### ISSUE TITLE
FormContext Invariant Violation

### ISSUE THREAD

**Issue by RyanPWalker** [bluebill1049/react-hook-form#101]
When trying to wrap my form in the `FormContext` component, I get the following error:

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

(brief) Code:
```
import useForm, { FormContext } from 'react-hook-form';

const AllApplications = (props) => {
    const methods = useForm();

    return (
        // pass all methods into the context
        <FormContext {...methods}>
            <div className={styles['application-container']}>
                <form
                    onSubmit={(values) => { console.log('values', values); methods.handleSubmit(submitForm(values)); }}
                    className={styles['form-container']}
                >
                    {...form inputs}
                </form>
            </div>
        </FormContext>
}

export default connect(
    mapStateToProps,
    mapDispatchToProps
)(AllApplications);
```

I want to use this to pass down the form methods to the different form pages, but I can't even try yet because this happens.  Potentially could be because I'm server side rendering this React, but the other methods have worked fine up until now.

Running latest version of Chrome, Node 10.16, React 16.8

**Comment by bluebill1049** [comment]
strange works in the demo: https://codesandbox.io/s/react-hook-form-form-context-zvfok

do you have a codesandbox i can do a quick test and see what's going on?

**Comment by bluebill1049** [comment]
Do you still having an issue with `FormCotext`?

**Comment by RyanPWalker** [comment]
Turns out I just needed to update to the latest version haha.  You're quick at making changes and updates 👌 Thanks
