### ISSUE TITLE
useFormContext missing return value type

### ISSUE THREAD

**Issue by ell10t** [bluebill1049/react-hook-form#104]
I know useFormContext is a new feature, but at the moment the return type is just `{}`, which gives me type errors:

![image](https://user-images.githubusercontent.com/35668113/60252074-85a7fd80-98c1-11e9-8bc2-93970735ecca.png)

Here's a hacky example that resolves the issues in `useFormContext.tsx`:

```ts
import * as React from "react";
import { FormProps } from './types'

// omit fallback required unless we update to typescript 3.5
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>
type FormContextValues = Required<Omit<FormProps, "children">>;

export const FormGlobalContext = React.createContext<FormContextValues>({} as FormContextValues);

export const useFormContext = () => React.useContext<FormContextValues>(FormGlobalContext);

export function FormContext(props: FormProps){
  const { children, ...rest } = props;
  return (
    <FormGlobalContext.Provider
      value={{
        ...rest
      } as FormContextValues}
      children={children}
    />
  );
}
```

Great work on the library! ❤️

**Comment by bluebill1049** [comment]
thanks @ell10t can you try to add type during `useForm()`? let me know if this fixes the issue 👍 

https://react-hook-form.com/api#Typescript

**Comment by bluebill1049** [comment]
I will take a look at this as well.

**Comment by ell10t** [comment]
Didn't help, `useFormContext()` and `React.createContext` currently define the context type as `{}`, my example above sets the type to `FormProps` which includes `register` etc.

**Comment by bluebill1049** [comment]
feel free to submit a PR if you have a solution to fix it too 👍

**Comment by bluebill1049** [comment]
thanks a lot, @ell10t here is the beta version: `react-hook-form@3.13.2-beta.1` let me know if this fixed those issues

**Comment by ell10t** [comment]
@bluebill1049 beta seems to be missing all types

**Comment by bluebill1049** [comment]
hmmm, I tested and works for me.

```
export interface FormProps {
  children: JSX.Element[] | JSX.Element;
  register?: (
    refOrValidateRule: RegisterInput | Ref,
    validateRule?: RegisterInput,
  ) => any;
  handleSubmit?: (
    callback: (data: any, e: React.SyntheticEvent) => void,
  ) => (e: React.SyntheticEvent) => Promise<void>;
  watch?: (
    fieldNames?: string | string[] | undefined,
    defaultValue?: string | string[] | undefined,
  ) => FieldValue | void;
  unSubscribe?: () => void;
  reset?: () => void;
  setError?: (name: string, type?: string, message?: string, ref?: Ref) => void;
  setValue?: (name: string, value: any) => void;
  triggerValidation?: (payload: {
    name: string;
    value?: any;
    forceValidation?: boolean;
  }) => void;
  getValues?: () => FormData;
  errors: DataType;
  formState: {
    dirty: boolean;
    isSubmitted: boolean;
    submitCount: number;
    touched: string[];
    isSubmitting: boolean;
    isValid: boolean;
  };
}

export type FormContextValues = Required<Omit<FormProps, 'children'>>;
```

let me know if you spot anything wrong.

**Comment by ell10t** [comment]
`.\node_modules\react-hook-form` just seems to contain an `.js` and `.es.js` file for me

**Comment by ell10t** [comment]
f82e588fe4d3112a6213c900feb586a748611ee7 removed `"declaration": true`, which stops output of the type files on build it seems

**Comment by bluebill1049** [comment]
oops... thanks @ell10t I need to read more on tsconfig... that was silly.

`react-hook-form@3.13.2-beta.3`

**Comment by bluebill1049** [comment]
thanks very much for your help @ell10t 🙏 I will include you as contributor once we published this patch.

**Comment by ell10t** [comment]
seems to have done the job :tada:

**Comment by bluebill1049** [comment]
publishing 🍾
