### ISSUE TITLE
FormContext typescript error

### ISSUE THREAD

**Issue by jasondibenedetto** [bluebill1049/react-hook-form#107]
Running into a typescript error on the latest build when trying to use `FormContext`.

Seems like an issue with the `touched` key in `formState`.

See below...
https://codesandbox.io/s/react-hook-form-ts-z0onr

**Comment by bluebill1049** [comment]
thanks @jasondibenedetto i am looing into that now

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-ts-0pvqn

**Comment by jasondibenedetto** [comment]
Thank you @bluebill1049

**Comment by bluebill1049** [comment]
Nah thank you for reporting ❤️

**Comment by bluebill1049** [comment]
wow you from Adelaide. nice

**Comment by jasondibenedetto** [comment]
Looks good to me 👍
