### ISSUE TITLE
unregister fields?

### ISSUE THREAD

**Issue by samlll42-github** [bluebill1049/react-hook-form#108]
We have a form that dynamically changes without being completely unmounted/remounted. Is there a way to unregister fields that may have been required, and may no longer be required?

Thanks

**Comment by bluebill1049** [comment]
hey @samlll42-github,

If you remove an input, it will get auto unregistered.

```
{willBeRemove && <input ref={register} name="test" />}
```

when `willBeRemove` set to false, the filed will be unregistered

**Comment by bluebill1049** [comment]
oops, I didn't' read your question clearly, you want to unregister even a field still mounted. currently, there is no `unregister` method. Curious why you guys doing so?

**Comment by samlll42-github** [comment]
good question :) We have a sign up form that switches mode and has different field requirements depending on the mode.

**Comment by bluebill1049** [comment]
Just some thoughts: curious why not build two separate forms, if they completely different. If they are similar should be able to toggle the fields.

**Comment by samlll42-github** [comment]
In our particular case we have just one field different out of a dozen...

**Comment by bluebill1049** [comment]
if you have to restrict which field to validate, maybe this API will be useful.

https://react-hook-form.com/api#useForm

`validationFields`

take a look, see if this helps :)

**Comment by bluebill1049** [comment]
is this doesn't, I can take a look into `unregister` and place in my todo list 👍

**Comment by bluebill1049** [comment]
@samlll42-github is any of my suggestion helps for you?

**Comment by bluebill1049** [comment]
going to close this issue now, feel free to open again for more questions

**Comment by bluebill1049** [comment]
hi @samlll42-github FYI `unregister` function has been released https://github.com/bluebill1049/react-hook-form/releases/tag/v3.18.2

**Comment by samlll42-github** [comment]
Just saw that! that's great thanks. We were having other problems with isValid but it looks like there has been a few fixes applied. Will give the latest release a shot. Thanks again for all the work!

**Comment by bluebill1049** [comment]
my pleasure, feel free to reopen issues. I will follow up 🙏
