### ISSUE TITLE
Small `register` API suggestion

### ISSUE THREAD

**Issue by jjenzz** [bluebill1049/react-hook-form#11]
Minor suggestion but it looks like if you used a closure then the `register` API could perhaps be simpler?

```js
function register(data = {}) {
  return (ref) => {
    // etc.
  }
}
```

```jsx
<input type="text" name="firstname" ref={register({ required: true })} />
<input type="text" name="lastname" ref={register()} />
```

**Comment by bluebill1049** [comment]
wow brilliant!!!! i will take a look and update :)

**Comment by bluebill1049** [comment]
thank you for your great suggestion : ) https://github.com/bluebill1049/react-hook-form/releases/tag/v2.0.0
