### ISSUE TITLE
onSubmit not working with yup

### ISSUE THREAD

**Issue by davidramos13** [bluebill1049/react-hook-form#111]
Hi! I was trying to update things and start using hooks more, and I liked the way forms are handled with your library, and more when it made me know yup, it looks clearer to me. But at this moment that way doesn't seem to work correctly.

**Describe the bug**
onSubmit is not working with yup, after the form is first validated (when the onChange event should be attached). It doesn't update validation status, it does only when I press to submit the form again. I don't see this problem if I avoid using yup.

**To Reproduce**
- The CodeSandbox for yup can be used (https://codesandbox.io/s/928po918qr)
- Change mode to onSubmit, and submit the form. Some errors are displayed.
- Start typing on first name field (required).

**Expected behavior**
The validation should update on input change if an attempt to submit the form was made (either to valid, or to show a different error).

**Additional**
Maybe this issue shown up after another one was fixed? I discovered it when searching issues here before writing this one: https://github.com/bluebill1049/react-hook-form/issues/23

**Comment by bluebill1049** [comment]
Thanks a lot for report the issue :)

I have patched the issue: `3.16.2-beta.1`

https://codesandbox.io/s/react-hook-form-validationschema-iui13

**Comment by bluebill1049** [comment]
Thanks a lot for report the issue :)

https://codesandbox.io/s/react-hook-form-validationschema-iui13

I have patched in `3.16.2-beta.2`

let me know if this fixed your issue.

**Comment by davidramos13** [comment]
Apparently it works now, thanks ;)

**Comment by bluebill1049** [comment]
thanks going to publish now

**Comment by RuiOrey** [comment]
I seem to have the same problem onSubmit not working

**Comment by ArifSanaullah** [comment]
> Thanks a lot for report the issue :)
> 
> https://codesandbox.io/s/react-hook-form-validationschema-iui13
> 
> I have patched in `3.16.2-beta.2`
> 
> let me know if this fixed your issue.

Can't find this mentioned sandbox. Can you please have look at the URL? It's 404.
