### ISSUE TITLE
Call handleSubmit even when validation fails

### ISSUE THREAD

**Issue by raff-r** [bluebill1049/react-hook-form#114]
Its my understanding that handleSubmit on calls the callback when validation is successful. Is there a way to call a function even when validation fails? We track all form errors when a user clicks submit so would like to know when there are errors and they click the submit button.

**Comment by bluebill1049** [comment]
yea you can.

you can add an onClick on the button

```
const { getValues } = useForm();
<input type="submit" onClick={() => getValues()} />
```

**Comment by bluebill1049** [comment]
I think you can refer to the `formState`

```
const { errors, formState } = useForm();

useEffect(() => {
  if (formState.isSubmitting) {
    console.log(errors)
  }
}, [formState.isSubmitting])
```

**Comment by raff-r** [comment]
I tried the useEffect method however on first submit button click errors is empty even though the form is invalid. Every click after that seems to get the correct errors

**Comment by raff-r** [comment]
i've put together a codeSandbox to illustrate whats happening https://codesandbox.io/s/friendly-bose-n8rjq

**Comment by bluebill1049** [comment]
Thanks for the codesandbox :) that really helps

https://codesandbox.io/s/great-bash-pmrqr

above is my version, see if it's working for you 👍

**Comment by raff-r** [comment]
Thanks for taking a look at this really appreciate it. It works great. 

I'm getting an eslint warning of React Hook useEffect has a missing dependency: 'errors'. Either include it or remove the dependency array. Is this something that I need to worry about? If include 'errors' as it mentions it calls onInvalidSubmit on every change after submitting the first time which isn't what we are looking for.

**Comment by bluebill1049** [comment]
To be honest I disable this rule when required at work. (at the line)

**Comment by raff-r** [comment]
That would great. Thank you again for your help

**Comment by bluebill1049** [comment]
how about this?

https://codesandbox.io/s/great-bash-pmrqr

**Comment by raff-r** [comment]
Works great, with no eslint errors. Thank you very much thats much appreciated!

**Comment by raff-r** [comment]
Would you be against incorporating invalid submit as part of handle submit? For example include another parameter which is if valid? 

I'm happy to see if I can work through your code and try to come up with a pull request.

**Comment by bluebill1049** [comment]
hey @raff-r 

no worries, glad I could help. I wouldn't recommend doing this for now (would like to keep it as simple as possible at this stage). but if more ppl request for this as a feature, I will work with you and others find a good solution. 

Thanks for offering time to help this project too. would love to see you contribute to this library int the future  :) 

thanks
bill

**Comment by raff-r** [comment]
No worries... thank you for your help

**Comment by heitoralthmann** [comment]
Hi guys!
I am also facing a scenario where I'd like _handleSubmit_ to skip validation.
Having two visible form fields, my _handleSubmit_ callback is supposed to hide one of them based on a custom condition. Being both fields marked as required, my _handleSubmit_ callback won't even get fired, given any of them is empty.

It'd be very interesting to have the ability to toggleValidation on _handleSubmit_. +1

**Comment by bluebill1049** [comment]
@heitoralthmann is `validationFields` going to help you with this?
