### ISSUE TITLE
How make select to submit non-string values?

### ISSUE THREAD

**Issue by Funkyskank** [bluebill1049/react-hook-form#118]
Is there a way to make `select` to submit non-string value?

This doesn't do a thing :
```jsx
<select
      onChange={e => {
        setValue('field', 1);
      }}
>
      <option value="1">1</option>
      <option value="2">2</option>
</select>
```
and we have empty string in form values.

**Comment by bluebill1049** [comment]
```
<select ref={register} name="test" onChange={e => {
  setValue('test', 1);
}}>
      <option value="1">1</option>
      <option value="2">2</option>
</select>
```

can you try above?

**Comment by Funkyskank** [comment]
it submits `"1"`

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-custom-input-k87mt

**Comment by bluebill1049** [comment]
ha, I remember you now, you fixed a typo on react hook form website. thanks, mate

**Comment by Funkyskank** [comment]
Yeah, greetings from Russia)

Guess found one more mistake in that example:
<Select name={label} ref={ref}>
must be <select ...

**Comment by bluebill1049** [comment]
hey, @Funkyskank is my approach to solve your problem.

**Comment by Funkyskank** [comment]
yes, thanks

**Comment by bluebill1049** [comment]
Thank you, feel free to open more issues :) please consider to leave start to support this little library 🙏 ❤️
