### ISSUE TITLE
[Question] Schema Validation

### ISSUE THREAD

**Issue by felipepastor** [bluebill1049/react-hook-form#120]
Hi all,

Thanks for create this amazing tool. I'm validating using yup and some how the library is triggering the error for nested object, but if I validate using the yup validator, it's working fine. Have you noticed this before?

The validation looks like this...
```
  information: yup.object().shape({
    priceVolume: yup.string()
      .some test
      .some other test
      .required(error.REQUIRED_FIELD_ERROR),
})

**Comment by bluebill1049** [comment]
thanks @felipepastor any chnace you can share a codesandbox?

**Comment by bluebill1049** [comment]
also what errors you are getting?

**Comment by bluebill1049** [comment]
hi @felipepastor how did you go with this issue?

**Comment by felipepastor** [comment]
I'll provide a codesandbox soon. I'm facing another issue. I'll ask in another ticket.

**Comment by bluebill1049** [comment]
I am going to close this issue now. feel free to re-open once you can supply a code sandbox with the issue. 👍
