### ISSUE TITLE
Split validation implementations out

### ISSUE THREAD

**Issue by stramel** [bluebill1049/react-hook-form#121]
**Is your feature request related to a problem? Please describe.**
The current size of the library is ~4.3kb min, gzipped which is far better than most form libraries. However, I think we could shave a bit more off the base library implementation by pulling the validation out. Currently this has 3 kinds of validation logic: generic validation, native validation, and schema validation (using Yup). 

**Describe the solution you'd like**
I think exposing only a generic validation in the base library would be sufficient. This would still allow others to use whatever validation library they choose to without adding the extra bundle size for those who don't use those features. 

We could pull native and schema validation out into small libs that would either plug in nicely to this library through the generic validation or add some kind of plugin system for it. I'm unsure that the plugin system would actually result in a smaller bundle size but may lead to easier validation integrations for other libs without the increase to the base library.

**Comment by bluebill1049** [comment]
Great suggestion @stramel 

I did think about this issue as well. I have the following mission when I am developing this library:

1. Great DX
2. Simple form validation (less code to write)
3. Better performance 
4. Smaller package dependency

Great DX is one of my primary goals, I want this library to be as easy as possible. I guess that's one of the reasons why I didn't split the validation methods into the plugin to reduce the package size. By giving validation method as an argument is slighter easier than figure out which plugin to import IMHO.

On the other perspective, by combining all the validation methods it allows me to re-use quite a bit of logic, especially with browser native validation. However, I do agree split the validation will reduce the size of the library. I think by moving out those dependencies we can reduce the library down to 3kb easily. 

My thoughts at the moment let's keep them together for now if the functionality grows, and then I can start to decouple that validation into `plugins`. 

Let me know your thoughts. I am happy to working split it apart when it requires. 🙏

**Comment by bluebill1049** [comment]
Going to close this issue now, we can revisit this later on :)
