### ISSUE TITLE
[Question] Material UI onChange triggering only in the second time

### ISSUE THREAD

**Issue by felipepastor** [bluebill1049/react-hook-form#123]
Hi,

I'm using Material-UI to build my inputs, but something that I noticed is when we use inputRef, a initialState object and value in the component, it's not triggering the change in the first change but only in the second and forward.

Here is an example based on your example using Material-UI.
https://codesandbox.io/s/react-hook-form-custom-input-ckz8t
You can check the console and please, let me know if I'm doing something wrong.

Thanks.

**Comment by bluebill1049** [comment]
is this what you after?

https://codesandbox.io/s/react-hook-form-custom-input-xsivu

(i have removed some of the unused code)

**Comment by felipepastor** [comment]
Updated with the current code I'm using. Does it make sense?

https://codesandbox.io/s/react-hook-form-custom-input-z331x

**Comment by bluebill1049** [comment]
I see, you mean `handleChange` is not triggered first input

**Comment by felipepastor** [comment]
Yes :)

**Comment by felipepastor** [comment]
What i find so far, if you defined the "number" as undefined, it triggers in the first input.

**Comment by bluebill1049** [comment]
ok because react-hook-form leverage uncontrolled input, if you remove `value`, it will work.

working version: https://codesandbox.io/s/react-hook-form-custom-input-6guwc

**Comment by bluebill1049** [comment]
i don't see what you try to achieve here tho. with react hook form you dont need `handleChange` unless you want to transform the input.

**Comment by felipepastor** [comment]
Uncontrolled works fine, but I want to transform the input fields value based on the language I select. For example US the format for thousands is 1,000 (comma) and for DE is 1.000 (dot), so if I change the language I should re-render based on the language transforming the fields. That's why the value is necessary for each input.

**Comment by bluebill1049** [comment]
oh i see

**Comment by felipepastor** [comment]
Do you think it's achievable?

**Comment by bluebill1049** [comment]
yes, we do that at work.

`onChange={e => e.target.value = transform(e.target.value)}`
transform is your function to do the number stuff

**Comment by felipepastor** [comment]
Got it, but I don't think it'll some the issue. Imagine the user already typed some number and then change the language (it's in a component up there somewhere else), I should change the number on the render something like.

```
<Input
  value={transform(number)}
  ...

**Comment by bluebill1049** [comment]
yea, we can use `setValue()` with `useEffect` when the mode change 👍

**Comment by bluebill1049** [comment]
feel free to reopen if this doesn't resolve your issue 👍

**Comment by lyvyu** [comment]
Hey guys,

I'm using Material UI and also ran into this bug just now, was wondering what the heck happened, like 10 mins ago everything was working fine, but then realised that I changed `defaultValue` to `value`.  The reason I changed this is that i have a `Reset` button which resets the form fields. Now the change only triggers the second time as I start to type. 
What would be the possible solution to this ?! 

P.S. I did put `setValue` but no luck at all.

Thanks in advance !!!

**Comment by bluebill1049** [comment]
@lyvyu you may want to use react-hook-form-input if you need to change defaultValue to value, because after using value it will become controlled component and then you will need onChange method and ect...

**Comment by lyvyu** [comment]
Hey @bluebill1049 , thanks for the response.

Look what I have here, everything works normally, but when I'm trying to reset form it just doesn't want to do so. I'm setting it to empty but it doesn't react at all.

Am I missing something ?! 

![image](https://user-images.githubusercontent.com/11527870/70244626-6ae58900-177d-11ea-8775-c3d65e38ef10.png)

**Comment by bluebill1049** [comment]
so is it working for you now?

**Comment by lyvyu** [comment]
Yeah, it's king complex(I guess) but it's working.

Thank you very much for the work and support !!!

**Comment by bluebill1049** [comment]
oh man my pleasure @lyvyu .
