### ISSUE TITLE
[Question] Continuous setError will Behave Incorrectly

### ISSUE THREAD

**Issue by wendyfu** [bluebill1049/react-hook-form#124]
**Describe the bug**
I'm currently using v3.10 and planning to upgrade.
However, I've noticed some stranger behavior when using the latest release (v3.18).
I'm making a select component using React Material Text Field which is a custom component (https://material-ui.com/components/text-fields/).
I do manual validation on the select component when the `onChange` occurred.
It seems that calling `setError(name)` continuously will "toggle" the error. Please refer to the reproduce step.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-custom-input-s02sk. This is a simple demo that will do validation on the select component each time `onChange` occurred. The select component will be displayed in red color if the selected item is invalid. The invalid item is 'Strawberry', 'Vanilla' and 'Chocolate' is valid.
2. The initial selected item should be `Strawberry`, and the select component is red-colored.
3. Click on the select component and choose 'Chocolate'. The select component error indicator is gone.
4. Click on the select component and choose 'Vanilla'. The select component is now red-colored again.
5. Click on the select component and choose 'Vanilla' again, the component error indicator is gone.
6. Now try to use v3.10 and repeat the process. The bug won't happened.

**Expected behavior**
Valid item shouldn't treated as error.

**Screenshots**
Step 1 and 2:
![Screenshot from 2019-07-10 21-32-06](https://user-images.githubusercontent.com/13144571/60977741-31d5f380-a35a-11e9-9c59-9cb3fc0b6c79.png)
Step 3:
![Screenshot from 2019-07-10 21-32-25](https://user-images.githubusercontent.com/13144571/60977775-3b5f5b80-a35a-11e9-8956-7248240c9156.png)
Step 4:
![Screenshot from 2019-07-10 21-32-53](https://user-images.githubusercontent.com/13144571/60977816-4adea480-a35a-11e9-8f44-f583a52d6252.png)
Step 5:
![Screenshot from 2019-07-10 21-33-10](https://user-images.githubusercontent.com/13144571/60977843-5500a300-a35a-11e9-9177-f8dae1e79284.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version 72.0.3626.119 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
<Unavailable>

**Additional context**
First thing first: please check my code implementation, am I doing it wrong?

**Comment by bluebill1049** [comment]
thank you very much for the detailed issue report. make my life so much easier! I think i know why this is happening will fix soon :)

**Comment by bluebill1049** [comment]
`react-hook-form@3.18.4-beta.1` looks like this are the fix, let me know if this fixes your problem and I will publish.

**Comment by bluebill1049** [comment]
i have one small suggestion: 

what about doing this instead: 

`register({ name: "materialSelect" }, { validate: value => value !== 'strawberry'});`

and in handle change, you can just use trigger validation

`triggerValidation({ name: 'materialSelect' })`

**Comment by bluebill1049** [comment]
i have published the fix 👍

**Comment by wendyfu** [comment]
Thank you so much for the fix Sir!
I've tested the latest version and it works gracefully.

**Comment by bluebill1049** [comment]
Thanks Wendy please consider leave a star to support this library and share in the community.  👍
