### ISSUE TITLE
Material ui input The first input is invalid

### ISSUE THREAD

**Issue by flycj** [bluebill1049/react-hook-form#128]
**Describe the bug**
I am using material-ui
No problem when I don't use react-hook-form
When I introduce react-hook-form and add register ref on TextInput, the first time the input is invalid (note: input when opening the page for the first time)

In the codeSandbox I reproduced this situation.
[CodeSandbox Link](https://codesandbox.io/s/react-hook-form-custom-input-mxm6i)

What should I do?
I need your help very much

**Comment by bluebill1049** [comment]
你好 @flycj , 你是不是写了`value` instead of `defaultValue`

因为react-hook-form 是uncontrolled.

看这个是不是解决你的问题

**Comment by flycj** [comment]
Thank you very much, it has been solved.
