### ISSUE TITLE
Custom Validation

### ISSUE THREAD

**Issue by rickysullivan** [bluebill1049/react-hook-form#129]
I have three checkboxes in my form, I need at least one to be checked for my form to be considered valid. How could I implement this?

**Comment by bluebill1049** [comment]
```
const validate = () => {
   const test1 = watch('test[0]');
   const test12= watch('test[1]');
   const test13= watch('test[2]');

  return (test1 || test2 || test3);
}

<input type="checkbox" name="test[0]" ref={ register({ validate }) } />
<input type="checkbox" name="test[1]" ref={ register({ validate }) } />
<input type="checkbox" name="test[2]" ref={ register({ validate }) } />
```

This is what's on top of my head. you want to do a quick test. The idea is to pass custom validation with watching other fields.

**Comment by rickysullivan** [comment]
Nice. Will give it a go.

**Comment by bluebill1049** [comment]
I will leave the issue open :) you can close it when you verify.

**Comment by rickysullivan** [comment]
Hmm. Not too sure what's going on. I can't get the form to submit.

https://codesandbox.io/s/new-tdd-s9yh0?fontsize=14

**Comment by bluebill1049** [comment]
```
function validate() {
    const test1 = watch("elements[0]");
    const test2 = watch("elements[1]");
    const test3 = watch("elements[2]");

    return !!(test1 || test2 || test3);
  }
```
will do :) it need to return boolean, my bad on the previous example

**Comment by bluebill1049** [comment]
@rickysullivan Did the above code solve your problem?

**Comment by rickysullivan** [comment]
Nope. Seems the code is intermittent. Will update codesandbox.

**Comment by rickysullivan** [comment]
@bluebill1049 [Codesandbox](https://codesandbox.io/s/new-tdd-s9yh0) updated. Form only submits when all 3 options are ticked or sometimes when only the first checkbox is selected.

**Comment by bluebill1049** [comment]
thanks taking a look now.

**Comment by bluebill1049** [comment]
looks like I have spotted the bug, https://codesandbox.io/s/gallant-turing-cbgfg

it's working as expected now

**Comment by bluebill1049** [comment]
beta version: `react-hook-form@3.18.6-beta.1`
if you could do a quick test 👍

**Comment by rickysullivan** [comment]
>Could not fetch dependencies, please try again in a couple seconds: Invalid tag name "react-hook-form@3.18.6-beta.1"

**Comment by bluebill1049** [comment]
this is the one with the source code: https://codesandbox.io/s/gallant-turing-cbgfg

**Comment by bluebill1049** [comment]
its good now :) https://codesandbox.io/s/gallant-turing-cbgfg

**Comment by rickysullivan** [comment]
Oh right. I thought you had tagged a beta release. It works now. I've changed the validate function:
```
const validate = () => {
    const test1 = watch("elements[0]");
    const test2 = watch("elements[1]");
    const test3 = watch("elements[2]");

    return test1 || test2 || test3 ? true : "Please choose an element.";
};
```

Just trying to show the error message now...

**Comment by bluebill1049** [comment]
I did tag a beta version, but somewhat it takes a while for it to work... 

what about this ? `!!(test1 || test2 || test3) || "Please choose an element."`

**Comment by bluebill1049** [comment]
for your case, it's probably easy to do inline:

https://codesandbox.io/s/musing-lichterman-lfxom

**Comment by rickysullivan** [comment]
Thanks man. Ok, so now the error only clears when all the check boxes have values.

![HookErrorIssue](https://user-images.githubusercontent.com/437480/61265566-d0dc6e80-a7e4-11e9-87cf-8cba783b1c52.gif)

**Comment by bluebill1049** [comment]
no worries man. https://codesandbox.io/s/sharp-knuth-6pf5r this shoould work now

**Comment by ASHFAQPATWARI** [comment]
@bluebill1049 There is one more issue with this:  https://codesandbox.io/s/sharp-knuth-6pf5r

Scenario:
1. Do not select anything and click submit, error will be shown
2. Select a checkbox and error will be gone as expected
3. Now in the same state(form already submitted once), Select one checkbox and then select another checkbox. Now uncheck both of them and error will still not be shown

**Comment by bluebill1049** [comment]
Thanks for the test: this should do the job now https://codesandbox.io/s/billowing-flower-11drx

**Comment by ASHFAQPATWARI** [comment]
@bluebill1049 The issue is gone. Can we have a new release?

**Comment by bluebill1049** [comment]
Nice 👍🏻 it’s the same version. Just the usage update 🙏🏻 Thanks for ur testing

**Comment by rickysullivan** [comment]
Works. Nice job.

**Comment by algebrathefish** [comment]
@bluebill1049 https://codesandbox.io/s/billowing-flower-11drx is gone

**Comment by nitaicharan93** [comment]
> I did tag a beta version, but somewhat it takes a while for it to work...
> 
> what about this ? `!!(test1 || test2 || test3) || "Please choose an element."`

const validate = () => {
    let arr = checkBoxes.filter((el, index) => !!watch(`elements[${index}]`) === true);
    return arr.length > 0 ? true : "message";
  };

**Comment by bluebill1049** [comment]
@nitaicharan93 i think you can use getValues instead of watch

**Comment by JohnLis** [comment]
@bluebill1049 link does not work: https://codesandbox.io/s/sharp-knuth-6pf5r
I have the same issue as here https://github.com/react-hook-form/react-hook-form/issues/129#issuecomment-511657723
Can you help?

**Comment by bluebill1049** [comment]
@JohnLis sure :)

here is option 1: https://codesandbox.io/s/eloquent-bose-b112y?file=/src/App.js with trigger and validation rules
options 2: using resolver/schema: https://codesandbox.io/s/determined-sun-fqcfd?file=/src/App.js

**Comment by JohnLis** [comment]
@bluebill1049 I used option 1
Thanks for the quick response.
