### ISSUE TITLE
[Question] Changing second select options based on first select value

### ISSUE THREAD

**Issue by manikantag** [bluebill1049/react-hook-form#133]
Hi,

First of all, thanks for the excellent library & the docs website especially :)

My requirement: I'm trying to change 2nd select box options based on the 1st select _(ex: say, on department change, employees select options should be changed)_.

For that in the component, I'm setting the sate using `useState` when `watch('deptid')` is changed. But it is causing `Too many re-renders` error.

```
Uncaught Invariant Violation: Too many re-renders. React limits the number of renders to prevent an infinite loop.
```

Demo code: https://codesandbox.io/s/thirsty-feather-klh4p (try changing 'Department', and see the error in Console). 

Code snippet from above link:
```js
function App({ depts, emps }) {
  const { handleSubmit, register, watch, getValues } = useForm();
  const [deptEmployees, setDeptEmployees] = useState([]);

  const deptChanged = watch("deptId");

  if (deptChanged) {
    setDeptEmployees(emps.filter(emp => emp.deptId === deptChanged)); // ----> causing error
  }
  ...
```

I'm not getting what is that I'm doing incorrectly. 

Thanks again.

**Comment by bluebill1049** [comment]
hi thanks for the kind words:

this is a React related question. i have fixed in the demo for you

https://codesandbox.io/s/nifty-swartz-uvdib

**Comment by manikantag** [comment]
Great, worked like charm. 

Now I get it why I don't need to set new state as `watch()` itself will do that, and that is why the render will occur again. And when I do new state change, it is causing the re-render and it again causes `watch()` to cause another re-render. Is my thinking correct?

**Comment by bluebill1049** [comment]
Watch doesn’t trigger re-render, it’s becuase one of ur if statement keep getting called. Check ur if statement 👍🏻

**Comment by bluebill1049** [comment]
If u find the package useful please consider staring and share in the community. Much appreciated 🙏

**Comment by manikantag** [comment]
Sure, thanks. 

> please consider staring and share in the community

I already did :)

**Comment by bluebill1049** [comment]
thank you very much 🙏
