### ISSUE TITLE
Wrong errors object type when using `validationSchema`

### ISSUE THREAD

**Issue by kilburn** [bluebill1049/react-hook-form#136]
When `validationSchema` is used, the type of the `errors` object is not 
```typescript
export type ErrorMessages<Data extends DataType> = {
  [Key in keyof Data]?: Error;
};
```
but:
```typescript
export type ErrorMessages<Data extends DataType> = {
  [Key in keyof Data]?: string;
};
```

**To Reproduce**
1. Run the [`validationSchema` example](https://github.com/bluebill1049/react-hook-form/blob/master/examples/validationSchema.tsx)
2. Do not fill in anything, just click submit
3. You get the serialized errors object back:
```javascript
Errors: {
  "firstName": "firstName is a required field",
  "age": "age must be a `number` type, but the final value was: `NaN` (cast from the value `\"\"`)."
}
```

**Expected behavior**
Either the `errors` object entries should conform to the `Error` type or the `errors` object itself should be typed as something like:
```typescript
export type ObjectErrorMessages<Data extends DataType> = {
  [Key in keyof Data]?: Error;
};
export type StringErrorMessages<Data extends DataType> = {
  [Key in keyof Data]?: string;
};
export type ErrorMessages<Data extends DataType> = ObjectErrorMessages<Data> | StringErrorMessages<Data>
```

**Comment by bluebill1049** [comment]
hey @kilburn,

thanks for the error report. sounds like you know a solution for this? any chance you would submit a PR? 🙏 

cheers
bill

**Comment by stramel** [comment]
I haven't tested this, but if this is true, you could probably get away with changing the value to `Error | string`. I'm going to try to take a look at the typings this weekend and see if I can improve upon them.

**Comment by kilburn** [comment]
I proposed the admittedly more complicated solution above under the assumption that you cannot mix "normal" validations and `validationSchema` in the same form (and hence either all of your errors are strings, or all of your errors are `Error` objects). If this is not the case, then `Error | string` si the actually better option.

Nonetheless, I haven't made a pull request because I've seen there are issues raised about typing errors for array fields and stuff, and I'm not familiar enough with all options to make a knowledgeable call about what the types should look like so they work in all cases...

**Comment by stramel** [comment]
I will see if I can cover this over the weekend. Some of it is pending on #134 	and #135 .

**Comment by bluebill1049** [comment]
thanks heaps @stramel I am focusing on issue #134 at the moment.

**Comment by bluebill1049** [comment]
hey @kilburn ,

@stramel have fixed the issue: ❤️ 👍 
https://github.com/bluebill1049/react-hook-form/releases/tag/3.8.12

let us know if that solved the problem.

thanks

**Comment by bluebill1049** [comment]
I am going to close this issue, we will keep track it in https://github.com/bluebill1049/react-hook-form/issues/135
