### ISSUE TITLE
nope-validator doesn't work with validationSchema

### ISSUE THREAD

**Issue by stramel** [bluebill1049/react-hook-form#141]
**Describe the bug**
When trying to use the `nope-validator` schema with the `validationSchema`, it doesn't actually trigger any of the validation.  

**To Reproduce**
https://9fy97.codesandbox.io/

**Expected behavior**
`nope-validator` should be a drop-in replacement for `yup`.

**Additional context**
Once this is working, I think it would be beneficial to recommend `nope-validator` over `yup` due to size and performance differences.

Slightly related to #121

**Comment by bluebill1049** [comment]
Thanks @stramel. I did talk to the author in terms of syntax and was confirmed to be the same and I just assumed it's working. lol, I will give a test, should be an easy fix. 

by the way, how did you go with the typescirpt issue?

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-validationschema-vfb7y

looks like this fix the issue.

**Comment by stramel** [comment]
It does appear to fix it from a quick smoke test.

**Comment by bluebill1049** [comment]
thanks @stramel 👍

**Comment by stramel** [comment]
@bluebill1049

The `firstName` and `age` (`age` if you remove the other restraints) doesn't seem to be validating properly for required.
The `website` and `age` fields seem to be validating on `change` instead of `blur`?

**Comment by bluebill1049** [comment]
hmm that's weird, it's the same logic... if nope is not going to work easily, i may take it off :(

**Comment by bluebill1049** [comment]
sorry, nope is gone from the website and support :(

**Comment by bluebill1049** [comment]
going to close this issue for now, until `nope-validator` come back with some updates :)
