### ISSUE TITLE
setError problems, possible related to #140

### ISSUE THREAD

**Issue by sheraz-sarwar** [bluebill1049/react-hook-form#145]
**Describe the bug**
I've found that setError when used as part of an submission handler causes unexpected behaviour. In many instances, the component rerenders then the entire error is deleted, in other (less consistent) cases you are unable to set a message. The former problem appears to affect versions `3.8.10` onwards and works correctly in `3.8.9`. Additionally, the error is only cleared when the first parameter of `setError` matches exactly the name of the input field.

This is linked to issue #140 and I've slightly adjusted the CodeSandbox example in that issue thread (https://codesandbox.io/s/react-hook-form-basic-n53gm) to create a reproduction of the problem, as below.

**To Reproduce**
1. Load the following sandbox: https://codesandbox.io/s/react-hook-form-basic-bij91
2. Note that on submission, no error is displayed
3. Change the dependency version of `react-hook-form` from `3.8.10` to `3.8.9`
4. On submission, an error is displayed

From the same issue thread (#140), you can use the other Sandbox example to see that a message cannot be set for the error:

https://codesandbox.io/s/seterror-problems-hqhpo

**Expected behavior**
A rerender does not cause the error to be cleared and a message can be set when using `setError` on submit.

**Comment by rkurbatov** [comment]
Yeah, the problem appeared again in 3.18.10+ (till 3.19.0)

**Comment by bluebill1049** [comment]
@sheraz-sarwar @rkurbatov sorry #140 fix doesn't resolve the problem correctly. 

This should be the right fixes now and I have provided with an example:

https://codesandbox.io/s/react-hook-form-basic-uinih

@sheraz-sarwar you can use `clearError` if semantically makes more sense (to clear an error). 

in addition, it's probably better to set a different `errorName` when validation is coming from the server, otherwise, it will be quite confusing.

**Comment by bluebill1049** [comment]
@sheraz-sarwar @rkurbatov you guys ok to close this issue as it's been resolved. feel free to reopen if there is still issue around it.

**Comment by EdwardBarton** [comment]
I'm encountering, what I believe to be, the same issue with v3.28.4. Manually setting an error via `setError` results in the `errors` object being empty upon component re-render, thus the error message never renders. Perhaps I'm just using the method improperly?

https://codesandbox.io/s/wonderful-pare-b2xvu

**Comment by EdwardBarton** [comment]
@bluebill1049  I'm encountering, what I believe to be, the same issue with v3.28.4. Manually setting an error via `setError` results in the `errors` object being empty upon component re-render, thus the error message never renders. Perhaps I'm just using the method improperly?

https://codesandbox.io/s/wonderful-pare-b2xvu
