### ISSUE TITLE
Add a build check for bundlesize

### ISSUE THREAD

**Issue by stramel** [bluebill1049/react-hook-form#146]
To ensure that features and configuration doesn't cause our bundle size to spiral out of control, it would be good to add a CI build check to keep us at an appropriate size.

We could use https://github.com/siddharthkp/bundlesize to handle this.

**Comment by bluebill1049** [comment]
nice one, I have added the script. going to make it into the build pipeline.

**Comment by bluebill1049** [comment]
it's working :) https://github.com/bluebill1049/react-hook-form/pull/148

**Comment by stramel** [comment]
@bluebill1049 Which ticket is this in?

**Comment by stramel** [comment]
Looks great! Might want to look at minifying the code before running bundle size. Generally, bundle size is measured in min, gzipped (gzipped is currently already applied)

**Comment by bluebill1049** [comment]
Done 👍

**Comment by stramel** [comment]
PERFECT! Thanks @bluebill1049!

**Comment by stramel** [comment]
@bluebill1049 

You mentioned that you copied the `set` command from lodash. When running bundlesize on the existing code, and got 4.42kb/4.81kb (es/cjs respectively). When I imported `set` from `lodash-es` I got 4.15kb/4.48kb (es/cjs). 

Swapping in `lodash-es` for `isString`, `isObject` and `set` dropped us to 4.14kb/4.47kb (es/cjs). 

What do you think? Less code we have to maintain

**Comment by bluebill1049** [comment]
I didn't copy `set`, I stole some of the regex and functions (lol). It would be a lot bigger if I get the whole thing.

At the stage, I think I still prefer 0 dependencies. (one of the features for the package) what you see is what you get (hehe)
as long as the package is less than `10kb` is still pretty good compared with other form libraries.
