### ISSUE TITLE
Better Type Hints for useForm(..).watch and .unregister's fieldName arguments

### ISSUE THREAD

**Issue by kaleabmelkie** [bluebill1049/react-hook-form#159]
The types definitions for `.watch` and `.unregister` functions in the **useForm.d.ts** file look something like:

```
    // ...
    unregister(name: string | string[]) => void;
    // ...
    watch: (fieldNames?: string | string[], ...
    // ...
```

These two arguments with types `string | string[]` are the ones I'm requesting an improvement for.

Just like clearError, setValue or most of the other methods in this file, it is possible to add the generic `Name | Name[]` type to them.

I understand that the reasoning behind making them of a `string | string []` type is so that it could be possible to watch or unregister nested and/or array filed names. 

However, doing something like this (👇) would me a much nicer DX (as most IDEs could provide auto complete hints for most of these field names):

```
    // ...
    unregister(name: Name | string | (Name | string)[]) => void;
    // ...
    watch: (fieldNames?: Name | string | (Name | string)[], ...
    // ...
```

I also understand that this change won't add much to static type checking (because `string` is a more general type than `Name`). But it provides Hints in IDEs.

***Additional (Probably Impossible) Request:***

*I'm not exactly sure how (or if it's even possible), but if it is possible to be specific enough with the type to remove string and also support arrays and nested fields, strictly with the correct type, it would be super nice. (¯\\\_(ツ)\_/¯ I know this is a little too far fetched).*

**Comment by bluebill1049** [comment]
hey @kaleabmelkie ,

thanks for the issue report :) sounds like you know what are you saying here, interested to submit a PR around this? otherwise, I will take a look at this later the day as well

**Comment by kaleabmelkie** [comment]
Sure, I'll work on it.

**Comment by bluebill1049** [comment]
Thanks buddy ❤️
