### ISSUE TITLE
[SSR] HTMLElement is not defined

### ISSUE THREAD

**Issue by revskill10** [bluebill1049/react-hook-form#16]
**Describe the bug**
Does this library support SSR ?
I got the error

```
HTMLElement is not defined
```

when using SSR.

**Comment by bluebill1049** [comment]
that's a bug @revskill10 i will fix that very soon. thanks for reporting

**Comment by bluebill1049** [comment]
can you please help test out this version?
npm i react-hook-form@2.1.15-beta.2

**Comment by bluebill1049** [comment]
hey @revskill10, i have published the fix https://github.com/bluebill1049/react-hook-form/releases/tag/v2.1.15. going to close this issue. feel free to reopen if found related issue.
