### ISSUE TITLE
Default values are not used when register is called before watch

### ISSUE THREAD

**Issue by GuillaumeAmat** [bluebill1049/react-hook-form#160]
**Describe the bug**

The default value of a watched field is not used if I register a custom field before.

**To Reproduce**

If I use:

1. `useForm` with `defaultValues`
2. `register` a custom field (in my case, not an actual form field, just to compute something)
3. `watch` a real form field

In that specific order, the default value of the watched field is not used, but if I switch 2 and 3, it is working fine.

It seems that the bug comes from the first line of the `watch` function:

https://github.com/bluebill1049/react-hook-form/blob/5e54a41e411c2fc710a6686199740e8a05b6dda6/src/useForm.ts#L442

`fieldsRef.current` is not empty because I used `register` before.

**Expected behavior**

Always use the default values, without having to specify them in the `watch` calls (as second argument).

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 68

**Comment by bluebill1049** [comment]
Thanks @GuillaumeAmat for the detailed issue report, i will sort this one out.

**Comment by bluebill1049** [comment]
@GuillaumeAmat any chance you could provide me with a codesandbox?

**Comment by bluebill1049** [comment]
made a patch `react-hook-form@3.20.4-beta.1`, please give a test. thanks

**Comment by GuillaumeAmat** [comment]
It works! Thank you @bluebill1049 👌

**Comment by bluebill1049** [comment]
cool @GuillaumeAmat I will get published soon 👍 thanks for the issue report

**Comment by bluebill1049** [comment]
merge and released https://github.com/bluebill1049/react-hook-form/releases/tag/v3.20.4

**Comment by bluebill1049** [comment]
close the issue whenever you are ready ❤️

**Comment by bluebill1049** [comment]
I will do it instead 😸
