### ISSUE TITLE
re-rendering of form after executing callback in handleSubmit may cause a memory leak

### ISSUE THREAD

**Issue by petercpwong** [bluebill1049/react-hook-form#162]
**Describe the bug**
If your callback to `handleSubmit` is an async function that causes the component to get unmounted, the call to `reRenderForm` may cause a memory leak.
https://github.com/bluebill1049/react-hook-form/blob/9487a365ee787737eb8806b9bc4b2c1ba9ef3887/src/useForm.ts#L589

**To Reproduce**
Pass an async function to `handleSubmit` that causes a state change in the parent component, which then unmounts the current component (in my particular case, it was a state change in mobx). React will then alert you there's a memory leak:

```react-dom.development.js:507 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.```

**Proposed fix**
One way to fix this may be to allow the callback to return a falsy value so `reRenderForm` will not be called after the callback finishes.

**Comment by bluebill1049** [comment]
interesting one, I have already try to prevent this at line https://github.com/bluebill1049/react-hook-form/blob/master/src/useForm.ts#L577 but for async function with `setState/useState` going to be bit tricky

**Comment by petercpwong** [comment]
Thanks for your quick reply!

> I have already try to prevent this at line https://github.com/bluebill1049/react-hook-form/blob/master/src/useForm.ts#L577 

My guess is that there's probably a race condition between the cleanup function calling `isUnmount.current = true` and `reRenderForm({});` getting called after the callback from `handleSubmit`

**Comment by bluebill1049** [comment]
I almost felt like a thing like this, probably should be better handle on app-level than the library itself. It's almost like when you doing a `fetch` or `promise`, you probably need to consider not to lead to memory leak.

**Comment by petercpwong** [comment]
Just did a quick test on my end and it seems to fix issues with async callbacks:

```
    if (isEmptyObject(fieldErrors)) {
      errorsRef.current = {};
      await callback(combineFieldValues(fieldValues), e);
    } else {
      errorsRef.current = fieldErrors as any;
    }

    if (isUnMount.current) return; /* move this here */

    isSubmittedRef.current = true;
    submitCountRef.current += 1;
    isSubmittingRef.current = false;
    reRenderForm({});
```

**Comment by bluebill1049** [comment]
oh cool!

**Comment by bluebill1049** [comment]
released the patch you happy to close this issue?

**Comment by petercpwong** [comment]
thanks!
