### ISSUE TITLE
Question: Can you configure validator to only run IF it has a value?

### ISSUE THREAD

**Issue by martinip86** [bluebill1049/react-hook-form#171]
Firstly, thanks for the lib - definitely making my life easier.

I've got a question regarding if it is possible to configure a validator to run only if there is a value in the field. 

I've had a read of the docs, but couldn't find what I was looking for (possibly just code blindness). https://react-hook-form.com/api/#register

As an example, I was attempting to configure a field which would only run the regex IF the value wasn't empty. In the example, the `pattern` regex will always trigger when the value is empty, which i guess makes sense.
```
register({
  required: false,
  pattern: /^[-+]?\d+(\.\d+)?$/,
})
```

If there is an alternative approach you are aware of, I'd appreciate your insights.
I could always tweak the regex to support an empty value if this isn't supported.

Thanks a lot.

**Comment by bluebill1049** [comment]
> Firstly, thanks for the lib - definitely making my life easier.

music to my 👂 

thank you.

you should be able to use `validate` function for your requirement.

the last validator on the list. https://react-hook-form.com/api#register

**Comment by martinip86** [comment]
Great thanks! I'll use that instead.
