### ISSUE TITLE
Errors variable informs about errors on unregistered/nonexistent fields

### ISSUE THREAD

**Issue by cfgj** [bluebill1049/react-hook-form#172]
Hi, I was trying to make a form using ant design, react hook form and yup libraries, but I encountered strange behaviour with values validation mechanism.

**Describe the bug**

I have manually registered fields and I update values via `setValue` with `shouldValidate` set to `true`. When I focus on any input and then I leave the input `errors` contains following data:
`{"name":{"message":"fullName is a required field","ref":{},"type":"required"}}` but I don't have any field named "name". After submitting the form everything is ok, and `errors` contains: `{"fullName":{"message":"fullName is a required field","ref":{},"type":"required"},"email":{"message":"email is a required field","ref":{},"type":"required"}}` .

The listing you can find below, but I've also prepared [codesandbox example](https://codesandbox.io/s/antd-react-hook-from-yup-5gujv-5gujv). 

```typescript
  const { register, handleSubmit, setValue, errors, getValues, formState } = useForm({
    validationSchema: yup.object().shape({
      fullName: yup.string().required(),
      email: yup.string().required() .email()
    })
  });

  React.useEffect(() => {
    register({ name: "fullName" });
    register({ name: "email" });
  });

  console.log(getValues(), errors, formState.isValid);

  return (
    <Form
      onSubmit={e => {
        handleSubmit(data => {
          console.log(data);
        })(e);
      }}>
      <Form.Item>
        <Input
          placeholder="full name"
          onBlur={e => setValue("fullName", e.target.value, true)} />
      </Form.Item>
      <Form.Item>
        <Input
          placeholder="email"
          onBlur={e => setValue("email", e.target.value, true)} />
      </Form.Item>
      <Form.Item>
        <Button type="primary" htmlType="submit">
          Signup
        </Button>
      </Form.Item>
    </Form>
  );
```

**Expected behavior**
`errors` variable should inform about errors on registered fields.

**Comment by bluebill1049** [comment]
Thanks for the detailed issue, I will take a look.

**Comment by bluebill1049** [comment]
Fixed https://github.com/bluebill1049/react-hook-form/releases/tag/v3.21.3

I have one suggestion for your code

```
<Input ref={regsiter} />
<Input innerRef={regsiter} />
```

can you try the above? if that works then you don't need to manually register the input and `setValue`

**Comment by cfgj** [comment]
Works like a charm, thanks :)

In antd controls, if you use `<Input ref={register} />` the reference of `Input` (not inner `input`) will be passed to the register function, so I should problably do like this:
```typescript
const inputRef = useRef();

useEffect(() => {
    register(input.current.input);
}, [input]);

return (
    <Input ref={inputRef} />
);
```

In order to shorten code it'd be a better idea to use wrapped Input. I have no better ideas at the moment.

**Comment by cfgj** [comment]
It seems to me thaht I've found another bug. When you type something in "full name" input and then you write valid email in "email" field, `formState.isValid` says the form is in invalid state, but when I press "Signup" button error on email field is removed. I'd point out that shouldValidate is set to true.

**Comment by bluebill1049** [comment]
I will take a look this.

**Comment by bluebill1049** [comment]
```
return (
    <Input ref={ref => inputRef(ref.current.input)} />
);
```

I saw your code nippet, can you shorten to above?

**Comment by bluebill1049** [comment]
thanks heaps for the error report! https://codesandbox.io/s/antd-react-hook-from-yup-5gujv-ys7yt (patched again)

**Comment by bluebill1049** [comment]
`3.21.4` patched

**Comment by bluebill1049** [comment]
https://github.com/bluebill1049/react-hook-form/releases/tag/3.21.4

**Comment by cfgj** [comment]
You forgot about removing error when field value is valid ;) check my PR out :)

**Comment by bluebill1049** [comment]
thanks @cfgj where is the PR?
