### ISSUE TITLE
Automation set up with `Yarn link` and Yarn link `react-hook-form`

### ISSUE THREAD

**Issue by bluebill1049** [bluebill1049/react-hook-form#176]
I am trying to set up automation env for `react-hook-form` and having an app running which references back to the source code in the `src` folder.

I have used `yarn link` at `/src` folder and then run `yarn link react-hook-form` at `/app` folder. however, when I start the app, I am getting this issue:

![image](https://user-images.githubusercontent.com/10513364/62208952-8d385600-b3db-11e9-92a1-57c1413cd035.png)

there is definitely no duplicated `react`.

wondering if anyone has experience or know how to fix this issue. PR welcome :) ❤️

**Comment by barrymay** [comment]
ah... I know this one.. (ran into it myself a bunch of times)(

Do what you did.... plus:

1. Go into your node_modules/react folder
2. Run yarn link
3. Go to your app where you're testing, and run yarn link react

The problem is that with hooks, you need to ensure the exact same react instance you built react-hook-form with is the one you're testing with.

**Comment by bluebill1049** [comment]
wow gonna give it a try! thanks @barrymay!

**Comment by bluebill1049** [comment]
`Go into your node_modules/react folder within the react-hook-form codebase`

oops there is no `react` in the node_modules folder, cause it's 
```
"peerDependencies": {
    "react": "^16.8.0",
    "react-dom": "^16.8.0"
  },
```

**Comment by bluebill1049** [comment]
OMG! @barrymay you are the GOD. It's working! thank you so much again ❤️

**Comment by barrymay** [comment]
(fwiw, it's something I'm definitely hoping they get rid of 16.9+, as it has hit me sooo many times)... But it's definitely the big tricky to know when linking with 3rd party packages

**Comment by bluebill1049** [comment]
oh yea I did face this issue before, but never thought about link `react` was the solution. really appreciated your help (as usual). ❤️  now I can start writing automation this weekend!
