### ISSUE TITLE
Checkbox gives value "on" instead of true by default

### ISSUE THREAD

**Issue by Nickman87** [bluebill1049/react-hook-form#179]
**Describe the bug**
I have an input which is a checkbox with no value assigned. Submitting this when the checkbox is unckecked gives me `false`, as expected. When I check the box however, is provides me with the value `"on"` instead of `true`.

**To Reproduce**
Check this sadbox: https://codesandbox.io/s/react-hook-form-basic-8zvj1

**Expected behavior**
If no value is given, it should alwys default to boolean values (`true`|`false`)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Chrome/Edge/Firefox
 - Version  76.0.3809.87 (64-bits)/42.17134.1.0/68.0.1 (64-bits)

**Additional context**
I see that `getFieldValue` is called with "on" as value, but I never entered this anywhere, so I'm not sure if this is a DOM qwirk or an internal issue?
I do think this should be covered by the lib for consistency :).

If I force the value to `undefined`, it _does_ give me the expected result.

**Comment by bluebill1049** [comment]
Hi @Nickman87,

Thanks for the detailed issue report. I think this is actually the correct behavior, if you inspect the checkbox with its value when you do not define a value for checkbox, it's default value will be 'on'. It's probably a good idea to give a value for input checkbox, but if you in a situation where you don't want to give a value, you can always convert 'on' to true. let me know if this makes sense.

**Comment by Nickman87** [comment]
@bluebill1049 I just find it confusing why I get `false` when it is off, but `"on"` when is is on...
I would either assume the default to be `true|false` or `"on"|"off"`, not a mix of both...

I fixed it for me, by assigning the value to `undefined`, but that also looks like just forcing the actual default value...

Is this a React thing, a browser thing or a react-hook-form thing the `"on"` value?

**Comment by bluebill1049** [comment]
hey @Nickman87, unfortunately, it's a browser thing. if you dig around the issues sections or looking at the commit history of that file (getFieldValue), my initial thought is just like yours until someone raised an issue about set to `true | false` because the HTML input checkbox is actually returning 'on' so I agree to follow the browser standard.

**Comment by bluebill1049** [comment]
going to close this issue for now, feel free to re-open or leave questions here
