### ISSUE TITLE
How to reinitialize the form?

### ISSUE THREAD

**Issue by 18601673727** [bluebill1049/react-hook-form#181]
Pardon my innocence for asking this silly question: 
How to reset the `defaultValues` like [this](https://jaredpalmer.com/formik/docs/api/withformik#enablereinitialize-boolean)? Or should I just take another existing approach?

**Comment by bluebill1049** [comment]
no worries :)

https://react-hook-form.com/api#reset

**Comment by 18601673727** [comment]
@bluebill1049 Thank you for the quick reply!

The problem is I don't mean to reset fields individually nor manually, it's something like reinitialize the whole form without doing comparisons from outside.

**Comment by bluebill1049** [comment]
yea `reset(defaultValue)` will do

**Comment by 18601673727** [comment]
Would you mind to enlighten me a little bit more bro? 
https://codesandbox.io/embed/react-hook-form-defaultvalues-sxwpx

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-defaultvalues-n5icx there you go bro

**Comment by bluebill1049** [comment]
hope this is what you after.

**Comment by 18601673727** [comment]
Hey, due to some reason `codesandbox` was not correctly saved, the code updated above explains my original intention. I don't want to plant buttons inside forms, they shall update themself automatically.

**Comment by bluebill1049** [comment]
I am confused. what do you mean update themselves automatically?

**Comment by bluebill1049** [comment]
want to chat in https://spectrum.chat/react-hook-form instead?

**Comment by bluebill1049** [comment]
i see you updated the code in the comment section now.

**Comment by bluebill1049** [comment]
```
useEffect(() => {
  reset(defaultValues);
}, defaultValues)
```

try this

**Comment by 18601673727** [comment]
> ```
> useEffect(() => {
>   reset(defaultValues);
> }, defaultValues)
> ```
> 
> try this

Well, it gives this error:

```
The above error occurred in the <Form> component:
    in Form (created by App)

    in div (created by App)

    in App


Consider adding an error boundary to your tree to customize error handling behavior.

Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by stramel** [comment]
Personally, I prefer to use the form reset event. Then just `onReset={() => reset(defaultValues)}` on the form.

**Comment by stramel** [comment]
Your useEffect is incorrect. 

```
useEffect(() => {
  reset(defaultValues);
}, [defaultValues])
```

**Comment by bluebill1049** [comment]
oops, thanks @stramel

**Comment by 18601673727** [comment]
Thank you all very much! But could someone explain me how to perform form reset events from outside or how to `useEffect` in this particular case?

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-defaultvalues-n5icx

**Comment by bluebill1049** [comment]
left message in spectrum as well for you

**Comment by 18601673727** [comment]
Cool, thanks in advance, this's exactly what I'm looking for!

**Comment by lifeeric** [comment]
Make logic, whenever you want to reset your input. just invoke the `reset` method

    import React from "react"
    import { useForm } from "react-hook-form"
    
    export default function App() {
      const { register, handleSubmit, errors, reset } = useForm()
      const onSubmit = data => {
        console.log(data)
        reset()
      }
    
      return (
        <form onSubmit={handleSubmit(onSubmit)}>
          <label htmlFor="firstName">First name</label>
          <input
            id="firstName"
            type="text"
            aria-invalid={errors.firstName ? "true" : "false"}
            name="firstName"
            ref={register({ required: true })}
          />
    
          <input type="submit" />
        </form>
      )
    }

cheer you!

**Comment by bryantobing12** [comment]
how about if the data comes from api?

for instance I have a form to edit post where i  need to prefill input text

first i'm fetching the post

```ts
const { data: post }  = usePost()

const { register } =  useForm({
    defaultValues: {
        title: post?.title,
        description: post?.description
    }
})

return (
    <>
      <input type="text" {...register('title')}/>
      <input type="text" {...register('description')}/>
    </>
)

```

the page will wait for the post data fetched from the api, and when the post data ready, the form didn't automatically reinitialize, and didn't prefill the input with post data

I try to use reset like this. but still not working

```ts
const { data: post }  = usePost()

const { register, reset } =  useForm({
    defaultValues: {
        title: post?.title,
        description: post?.description
    }
})

useEffect(() => {
   // this will reset to defaultValues as said in the docs
   reset()
}, [post])


return (
    <>
      <input type="text" {...register('title')}/>
      <input type="text" {...register('description')}/>
    </>
)

```

**Comment by Moshyfawn** [comment]
The `reset` method call with the new default values is the way to do it with RHF.

You can define the `defaultValues` object and use it as both `useForm` `defaultValues` and the `reset` method value

_P. S. don't forget to add the `reset` method as a `useEffect` dependency_

**Comment by bryantobing12** [comment]
@Moshyfawn was actually doing that eventually. but need to wrap the defaultValues inside use memo to prevent unnecessary rerender and reassign

ended up with the code like this..

```ts
const { post } = usePost()

const defaultValues = useMemo(() => {
  return {
        title: post?.title,
        description: post?.description
  }
},[post])

const { register, reset } =  useForm({
    defaultValues
})

  useEffect(() => {
     // this will reset to defaultValues as said in the docs
     reset(defaultValues)
  }, [post, reset])
```

but i would say that it's not so pretty because it increase the complexity in the component.

i came from formik. i think they handle this thing pretty good with `enableReinitialize` api
https://formik.org/docs/api/formik#enablereinitialize-boolean where we don't have to do reset manually and have more configuration.

I was hopiing that we can also do that in react-hook-form and rhf will automatically detect the changes on defaultValues automatically, something like this

```ts
const { register, reset } =  useForm({
    defaultValues,
    enableReinitialize: true
})
```

**Comment by chidimo** [comment]
@bryantobing12 this is exactly what I was looking for. `enableReinitialize`. In the absence of that, I'll use your method.
