### ISSUE TITLE
Add .getProps() to useForm

### ISSUE THREAD

**Issue by kaleabmelkie** [bluebill1049/react-hook-form#184]
**Is your feature request related to a problem? Please describe.**
I want easy access to the `defaultValues` I've passed in `useForm`'s props

**Describe the solution you'd like**
A new `.getProps()` method:
```tsx
const form = useForm({
  mode: 'onBlur'
  defaultValues: { foo: 'bar' }
})

// what I want:
form.getProps().defaultValues; // { foo: 'bar' }
form.getProps().mode; // 'onBlur'
// and so on
```

**Comment by bluebill1049** [comment]
Hi @kaleabmelkie 

Could you just hoist your default values to the top?

```
const defaultValues = { foo: 'bar' };

const form = useForm({
  mode: 'onBlur'
  defaultValues: { foo: 'bar' }
})
```

**Comment by kaleabmelkie** [comment]
Yes, I have considered doing that. I just thought it would be cleaner to have something like .getProps, esp. in typescript projects.

Generally, I would have to do something like this in a .tsx file:

**Comment by kaleabmelkie** [comment]
I took the liberty to submit a pull request for this (#185) ... I hope it's okay.

**Comment by bluebill1049** [comment]
Thanks for the PR. I tempt to reduce more methods if I can in order to keep the API list small. I don't see much value on this `getProps()` method at this stage. but let's get the other two core contributors' thoughts as well @barrymay @stramel : what do you guys think of this feature?

**Comment by kaleabmelkie** [comment]
I would like to mention one more advantage for this design: It allows access to the default options in some scenarios:

Example:

```tsx
import { Props } from 'react-hook-form/dist/types'

const config: Props<T> = { defaultValues: { foo: 'bar' } };

const form = useForm<T>(config)

config.mode // undefined
config.submitFocusError // undefined
```

Instead, it could be:
```tsx
const form = useForm<T>({ defaultValues: { foo: 'bar' } })

config.getProps().mode // 'onSubmit'
config.getProps().submitFocusError // false
```

**Comment by stramel** [comment]
@bluebill1049 I think I'm against this change. It expands the public API surface, bundlesize, and code that we have to maintain to handle something that is relatively arbitrary without this change. The only thing that I see being useful of that config object would be the `defaultValues`.

```
const defaultValues = { foo: 'bar' }

const form = useForm({ defaultValues })
```

**Comment by bluebill1049** [comment]
That was what I thought as well. 👍
