### ISSUE TITLE
Ability to register custom components

### ISSUE THREAD

**Issue by KevinKelbie** [bluebill1049/react-hook-form#187]
**Is your feature request related to a problem? Please describe.**
I'm trying to register a custom dropdown component ([react-dropdown](https://www.npmjs.com/package/react-dropdown)). It doesn't seem to work, please add an ability to register custom components like this.

**Describe the solution you'd like**

I don't know what the exact API would look like but here is what I would like to do

    <Dropdown options={[
            ...
        ]} 

        ref={register(
            onClick: { // the updated state occurs on an onClick event
                (e) => return e.value
            }
        )}
    } />

It would also need to change `onChange` also for other use cases so maybe this can be generalised in some way.

A possible issue could arise when you use the `required: true` because how that would work for a custom component would need to be different since `react-hook-form` wouldn't know where to look for that information. 

**Describe alternatives you've considered**
I currently just store it separately from `react-hook-form` inside of a `useState` hook

**Additional context**

**Comment by bluebill1049** [comment]
we do support custom `register`

```
useEffect(() => {
  register({ name: 'dropDown' }, { required: true })
}, [register])

<Dropdown options={[
        ...
    ]} 
 onChange={(value) => { setValue('dropDown', value) }}
} />
```

https://react-hook-form.com/get-started

section: working with UI component

**Comment by KevinKelbie** [comment]
very cool, thanks for the speedy reply!
