### ISSUE TITLE
fieldarray

### ISSUE THREAD

**Issue by webmobiles** [bluebill1049/react-hook-form#19]
hello
there are plans to add field array like reduxform? or simply with this lib, it's needed another techniques ?

**Comment by bluebill1049** [comment]
hey Dave,

I have an example here: https://github.com/bluebill1049/react-hook-form/blob/master/examples/arrayFields.tsx

and live demo here: https://codesandbox.io/s/6j1760jkjk

let me know if that solves your problem.

cheers
bill

**Comment by webmobiles** [comment]
that is great !! thanks  ,well done !

**Comment by bluebill1049** [comment]
nice👍 feel free to ask questions or feedback here, I will try my best to answer and resolve problems 👍
