### ISSUE TITLE
Integrate with Pika CI for PRs

### ISSUE THREAD

**Issue by stramel** [bluebill1049/react-hook-form#191]
**Is your feature request related to a problem? Please describe.**
The ability to test package changes without the need to publish them.

**Describe the solution you'd like**
Pika CI enables this for all PRs. https://www.pika.dev/cicd

**Comment by bluebill1049** [comment]
wow

**Comment by bluebill1049** [comment]
installed need to read more about it. thanks for the suggestion :)

**Comment by bluebill1049** [comment]
going to close this issue, it's installed

**Comment by stramel** [comment]
Looks like it is working! Thanks for installing it!

Side Note: Looks like CodeSandbox is having an issue with the URL installs right now. Locally, I had no issues. I already contacted the owners about it. https://twitter.com/stramel89/status/1159161464277667841
