### ISSUE TITLE
Arrow function in /dist folder

### ISSUE THREAD

**Issue by crabkiller** [bluebill1049/react-hook-form#192]
I found some arrow functions in `/dist` folder, I think maybe it should be transformed to ES5's general function?

**Comment by bluebill1049** [comment]
If you need to support old browsers, you can use a version with `ie11` tagged.

**Comment by bluebill1049** [comment]
eg: `3.21.4-ie11`

**Comment by bluebill1049** [comment]
check the FAQ section at https://react-hook-form.com/faq

I will update website at the FAQ as well with ie taged release

**Comment by bluebill1049** [comment]
latest react-hook-form@3.21.9-ie11
