### ISSUE TITLE
Field watch not registering correctly when blurring without typing

### ISSUE THREAD

**Issue by Nickman87** [bluebill1049/react-hook-form#195]
**Describe the bug**
I have a form with multiple fields (important!) where at least one field is filled in.
Another field is empty and when I focus this field, and then defocus it (causing the onBlur to trigger, marking the field as touched), my watch will no longer correctly register.

**To Reproduce**
https://codesandbox.io/s/react-hook-form-watch-after-empty-defocus-wydwj

The first field `ignore me` is already filled. If you click in the second field and start typing, the value will be appended to the right.
If you focus the second field and blur it before typing in it, the value will not appear on the right, the watch is never registered nor triggered.

**Expected behavior**
As I did not do anything to the field (and even if I did) I would still expect the watch to correctly fire updated no matter how many times I focus or defocus the input.

**Screenshots**
I think this piece of code might be a good starting point to debug it, but I cannot find a fix for now:
![image](https://user-images.githubusercontent.com/870416/62651626-b7e55a00-b959-11e9-85bc-f925cca26e44.png)
That line makes sure the component is updated when I start typing (on the initial focus). After blurring the input once, this `shouldUpdateState` is no longer set to true, causing the component to not rerender and thus not start watching. This is because watches are only registered if there is an actual value (probably for performance, but the fallback here does not seem to be flawless).
![image](https://user-images.githubusercontent.com/870416/62651798-17436a00-b95a-11e9-830d-97e9c2fe8a08.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by bluebill1049** [comment]
thanks for the detailed issue report  i will looking into it.

**Comment by bluebill1049** [comment]
fix and patched https://github.com/bluebill1049/react-hook-form/releases/tag/v3.21.10

thanks!

**Comment by bluebill1049** [comment]
close the issue when you verify 🙏

**Comment by bluebill1049** [comment]
happy to close this one?

**Comment by Nickman87** [comment]
@bluebill1049 I have not had the chance to test out the fix yet. When I do I will come back and close the issue :). I will try to check it out tonight.

**Comment by Nickman87** [comment]
It seems to be working now, thanks!
