### ISSUE TITLE
watch not triggered on change

### ISSUE THREAD

**Issue by gmpetrov** [bluebill1049/react-hook-form#198]
Hi @bluebill1049,

First thanks a lot for this great library !

I'm trying to get all form values on change the watch function is not triggered as expected.

[Here](https://codesandbox.io/s/react-hook-form-watch-rs221) is a demo using v3.21.10 
I think it should logs on every input's changes.

Note that it works well when using v3.18.14

**Comment by bluebill1049** [comment]
Thanks 👍 fixing

**Comment by bluebill1049** [comment]
Thanks for reporting. fixed v3.21.11, once I have more automation test. This should happen less often.

**Comment by bluebill1049** [comment]
https://github.com/bluebill1049/react-hook-form/releases/tag/v3.21.11

**Comment by gmpetrov** [comment]
Wow you are fast ⚡️👍 thx !!

**Comment by bluebill1049** [comment]
pleasure! thanks for reporting. ❤️
