### ISSUE TITLE
Run Prettier over Docs? 

### ISSUE THREAD

**Issue by damassi** [bluebill1049/react-hook-form#2]
Thanks for this lib! The patterns look great.

The docs are a bit difficult to read however because the code samples seem to be formatted by hand. Prettier supports Markdown, which would improve readability overall. Also the code samples are a bit small text-size-wise and line-height-wise, requiring a bit of squinting.

**Comment by bluebill1049** [comment]
thanks @damassi i am going to work on that. 🙏

**Comment by bluebill1049** [comment]
hey @damassi i have improved on the API page, let me know if its better now.

https://react-hook-form.now.sh/api

thanks mate

**Comment by damassi** [comment]
There are still a couple issues:
- If you copy and paste that top snipped into prettier it comes back with syntax errors
- I've fixed them here, but note the 80 character column width, which is more readable for docs, and Prettier's formatting, which cleans up some of the run-ons. See [this playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwHIdTy6AdKDbPfAVwGc4AYrlpUa9RmRgBaABYQIAaykVhrKGwrco5VNHwBNCNxxCc6ABQBKfMDb58kKLwLB8jAOapncHABp8MiRQACYANnAAytwARuioMP4A7iQwYDL+PtQ4vPgAvvgAvDz8phaWANx2+AD01QZGOPgqZvi8MXGUWjp6iTKoafiJqKGh+KhQAG6KcPgkFPCNbWBgcLy8mqMTJKGowSm66lD2js740FGx8YX45nswJNYFAHw2DtC8EOEAdKEQ7rcpB55fBVKq1ercBxBQYpAbjYKoCa7bjbMZQTDcAjRACe+EwJDW+BgMhmUBI6BmEAoRJJaIxMCqJ0+cB+f3MyVSMnMdDgAA9yZhwnRLNZQUc3HAYMYjuYqvZwYEQuELh1BsNNttdvs9NiGnTMTlonBmpSoCr4nL8AAeZq0d7teIFYCKsKRB0wcznd2WXIvewg8X+mzVABUELVIwCJAmMxgEAlnm8jV1xn1BHGcYlklk8iUtv8OLRUwUM0tQfsxJmHi8CyaXRgBzVxIl1IJNJmJBw7m4FNg+BD1VyZet43pROxmDgBRYIHgvIZIHwZIp05AfIF4RnLadLcKL1c1aT5gPxryPuB1Sew+AobRYFC3GCMy2OzujaGzcYAEduKhGMEmlQOBQgA3AzkrRZ7hCTsAJkGB0FGYcgxfLUGz0HBuHCHJ+0HYcrVHTFx0nVc5wXJdySnGd1ywcJiB-P84GCLdGAoHcWL3V5DwWY8W38b9f3-JAiQwuB-HQEheSEgBGAAGM98nyS9r0yXBeC+ajBRmAAyLT6CtXh8SgJ4ABU+hyCggJAsYcn4hjgitaoDKCJ46CHQN-Xw9FCJgCdKJANpLjIy8AyDBzbSvcVLDYXIQF8EAIEwNCnGQUBO2oRIAAVOwQXhkBAaMIF2WKQGiHAyBLGAInxMBxncZAYBEuK4IQgB1Pp4CclYIhy+JEXibE8rANZivGfg8Aysr3HE5AKG2fg4oAK14XkACEyrACqIgogAZcY4BmubRJAJbeQiWrwgARW4CB4AO0J5pAfFsh8PLohIHFfigYrMBwDMWt2YlkAADhkuKfogfgWrKzA8p+1YfBjYrbMYCaSCmkg7oe-g4nqxr-POuArpu-akFm+6jvuaJ-uCQGkAAJjihqSGGWqAGEaGmlAoGgfa4r4OBjPe3LScO3JciAA).

- These examples are all syntactically invalid (no closing tag), and the formatting is off with the line breaks: 

<img width="339" alt="Screen Shot 2019-03-23 at 3 33 50 PM" src="https://user-images.githubusercontent.com/236943/54872432-1df18c00-4d81-11e9-92d6-bcda209ba29c.png">

Maybe if the `examples` column was removed and the examples themselves were pushed into the `description`? Then they'd have some room to breathe, since there'd be extra width available.

**Comment by bluebill1049** [comment]
you have the cached version @damassi 

![image](https://user-images.githubusercontent.com/10513364/54872683-e84db100-4e1b-11e9-9ba2-6effd488bc1f.png)

**Comment by bluebill1049** [comment]
reading rest of your comments now. 👍 thanks for checking mate

**Comment by bluebill1049** [comment]
![image](https://user-images.githubusercontent.com/10513364/54872688-1a5f1300-4e1c-11e9-8662-24f1c7c041e0.png)

i have also adjust the line height of example code.

**Comment by damassi** [comment]
Ah! just cleared cache via devtools, this looks much better 👍 

Will close this issue.

**Comment by damassi** [comment]
One thing to note tho is that this kind of comment within the body of JS is invalid:

```
{/* your form submit function which will invoke after successful validation */}
```

**Comment by bluebill1049** [comment]
thanks heaps @damassi  feel free to leave more issues alone the way, i am still cleaning up the website and repo. to be honest i rushed the website...

**Comment by bluebill1049** [comment]
yea @damassi the plugin i am using for syntax highlight is not perfect, without {* *} it think it as the code, but you are right, maybe its better even color is wrong

**Comment by bluebill1049** [comment]
i will change them to // ignore the color 👍

**Comment by bluebill1049** [comment]
![image](https://user-images.githubusercontent.com/10513364/54872716-b2f59300-4e1c-11e9-9c7c-628a5cc3a58d.png)
i guess its better than when you copy and paste things break.
