### ISSUE TITLE
Using useReducer will have `errors` as  an empty object.

### ISSUE THREAD

**Issue by github0013** [bluebill1049/react-hook-form#204]
**Describe the bug**
`errors` is empty if it's coming from `useReducer`

**To Reproduce**
https://codesandbox.io/s/my-app-wuloq

**Expected behavior**
`errors` before `useReducer` seems to have correct properties.  I am expecting to have the same values in errors coming from `state`.

```tsx
// https://codesandbox.io/s/my-app-wuloq
// App.tsx

  // This has error properties when the form is invalid
  console.log("coming directly from useForm - errors:", errors)
  // This seems it's always empty
  console.log("coming from state - errors:", state.errors)

```

**Comment by bluebill1049** [comment]
Are you try to do global state management with form data? 
can I recommend you try out `little-state-machine`?

https://github.com/bluebill1049/little-state-machine

Demo: https://codesandbox.io/s/lrz5wloklm

**Comment by bluebill1049** [comment]
This is a React question with useReducer. 
when you run reduce, errors will always be on the initial render. if you want to update errors. you should run action to update it. but I will still recommend little state machine, you will find it much easier.

**Comment by github0013** [comment]
> when you run reduce, errors will always be on the initial render

Is it `useReducer` limitation?

```js
// https://reactjs.org/docs/hooks-reference.html#usereducer
const [state, dispatch] = useReducer(reducer, initialArg, init);

```

I am still trying to figure out why the second arg `initialArg` has different values when it comes out of `state`.

I see other state values except `errors` are working as expected in the codesandbox example.

```tsx
// https://codesandbox.io/s/my-app-wuloq
// App.tsx

  const [state, dispatch] = React.useReducer(reducer, {
    errors,
    register,
    handleSubmit,
    count: 0,
  })

```

**Comment by github0013** [comment]
or ... 

### FormContext
https://react-hook-form.com/api/#FormContext

is more like what I need... (just found it)

**Comment by github0013** [comment]
I noticed I didn't explain what I was seeing.   I was trying to show an error message and came across this problem.

https://codesandbox.io/s/my-app-wuloq
Please first submit without entering anything.   It then usually shows and an error message like below.

```tsx
// use-reducer/Input/index.tsx

      <input name={name} ref={register({ required: true })} />
      <p>{errors.userName ? "error" : null}</p>

```

But this actually doesn't show anything because `errors` coming from the state is empty object for some reasons.

**Comment by bluebill1049** [comment]
I haven’t looked at ur codesandbox, but I have a feeling u didn’t update ur reducer with action which contains error.

**Comment by github0013** [comment]
Oh, right, the initial will stay as is `until` it's updated.
