### ISSUE TITLE
Register API should not have to take options that are native input attributes

### ISSUE THREAD

**Issue by sonhanguyen** [bluebill1049/react-hook-form#24]
Instead of `<input ref={register({ required: true })}>`
I prefer `<input required ref={register}>`

**Comment by bluebill1049** [comment]
It's for validation to check if it's required or not. you can do that as well

```<input required ref={register} required />```

do the following 
```<input ref={register({ required: true })}>``` 

if you want to have custom error message rather than native behavior.

**Comment by bluebill1049** [comment]
those extra options within the `register` argument could be useful for other validation too:

eg:

<input name="test" ref={register({ validate: (value) => value=== 'bill'  })} />
{errors.test && 'name have to be bill'}

**Comment by sonhanguyen** [comment]
I assume inside `register` you could just read them from the input? I'm not saying those validations are not useful, just we should be able to have them simply by having those attributes on the input (if the behavior is exactly the same). Too implicit?

**Comment by bluebill1049** [comment]
yea register will hold all the input ref, so access value or error field ref is much easier. you can focus on error field without any extra work too. that's just my example, you can build your validation rules external and plug them in.

```
improt validateName from 'utility/validateName';

<input name="test" ref={register({ validate: validateName, minLength: 5 })} />
{errors.test && 'name have to be bill'}

```

**Comment by sonhanguyen** [comment]
Maybe my point isn't clear enough. Things like `pattern`, `minLenght` and `required` are already implemented in the dom API so people probably prefer to use those things. By removing those you can simplify the code and encourage web standard imo. You can just call `input.checkValidity()` instead of having to do the checks yourself.

**Comment by bluebill1049** [comment]
yea I get your point, you can use standard validation if you want. the choice is yours.

`<input name="input" ref={regsiter} />`

**Comment by bluebill1049** [comment]
hey mate, going to close this issue. let me know if you still have concerns, we can continue the discussion. 

cheers
bill

**Comment by portfolioris** [comment]
This would provide a great way to enable progressive enhancement. You use web standards, which will almost always work, even if loading or executing JS fails (or if users choose to disable JS). If it does execute, react-hook-form would take over, and apply custom validation instead. You set a `novalidate` attribute on the `<form>` tag by script, so the browsers knows you've taken over the validation.
