### ISSUE TITLE
Intercepting ref

### ISSUE THREAD

**Issue by sonhanguyen** [bluebill1049/react-hook-form#25]
**Is your feature request related to a problem? Please describe.**
Let's say for whatever reason, I need to pass my own `ref` function to an input, we currently don't have a way to do that.
**Describe the solution you'd like**
`<input ref={register({ ref })}>`

**Comment by bluebill1049** [comment]
you mean if you want to access the ref?
```
const myRef = useRef(null);
<input ref={(ref) => { 
  myRef.current = ref; 
  register(ref); 
}} />
```
same for class component

**Comment by sonhanguyen** [comment]
Oh yeah, that works, but could it be more convenient? :)

**Comment by bluebill1049** [comment]
yea probably, I guess it's one of the side effects by using ref for the package, but what you get out of it is much simple API and better performance, you don't have to wrap component around your input and re-render all the time.

**Comment by bluebill1049** [comment]
going to close this issue as well, feel free to leave more questions. billy :)

**Comment by VilleMiekkoja** [comment]
> you mean if you want to access the ref?
> 
> ```
> const myRef = useRef(null);
> 
> <input ref={(ref) => { 
>   myRef.current = ref; 
>   register(ref); 
> }} />
> ```
> 
> same for class component
> 
> this.test = React.createRef();
> 
> ```
> <input ref={(ref) => { 
>  this.test = ref; 
>   register(ref); 
> }} />
> ```

TS2540: Cannot assign to 'current' because it is a read-only property.

**Comment by erogleva** [comment]
> > you mean if you want to access the ref?
> > ```
> > const myRef = useRef(null);
> > 
> > <input ref={(ref) => { 
> >   myRef.current = ref; 
> >   register(ref); 
> > }} />
> > ```
> > 
> > 
> > same for class component
> > this.test = React.createRef();
> > ```
> > <input ref={(ref) => { 
> >  this.test = ref; 
> >   register(ref); 
> > }} />
> > ```
> 
> TS2540: Cannot assign to 'current' because it is a read-only property.

I just had the same issue: the type should be defined as `const inputRef = useRef<HTMLInputElement | null>(null);`, then the TS error doesn't appear anymore (see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31065#issuecomment-446425911)

**Comment by bluebill1049** [comment]
Thanks for sharing @erogleva

**Comment by chardypilot** [comment]
Hi Guys, 

How do you do it when the input element is wrapped by the <Controller />? 
I'm using it with ionic react and yupResolver and I to access the methods of the ionic component I'm wrapping.
Passing ref through the render prop (like on the example below) doesn't work. It does trigger an error on submitting as if the input field was empty or null


`<Controller control={control} name="email" render={({onBlur, onChange, value, ref})=>(
    <IonInput color="dark" onIonBlur={onBlur} onIonChange={onChange} value={value}
        mode="md" autocomplete="email" clearInput={true} ref={ref}
        type="email" inputmode="email"
    />
)}
/>`

**Comment by chardypilot** [comment]
Hi Guys,

How do you do it when the input element is wrapped by the ?
I'm using it with ionic react and yupResolver and I to access the methods of the ionic component I'm wrapping.
Passing ref through the render prop (like on the example below) doesn't work. It does trigger an error on submitting as if the input field was empty or null

`<Controller control={control} name="email" render={({onBlur, onChange, value, ref})=>( <IonInput color="dark" onIonBlur={onBlur} onIonChange={onChange} value={value} mode="md" autocomplete="email" clearInput={true} ref={ref} type="email" inputmode="email" /> )} />`

**Comment by chardypilot** [comment]
Hi Guys, 

Is there a way to achieve this same behavior with the Controller component? When I pass ref to the controlled element, handleSubmit doesn't get the input data anymore.

Thanks beforehand for your help and insight.

`<Controller control={control} name="email" render={({onBlur, onChange, value, ref})=>( <IonInput color="dark" onIonBlur={onBlur} onIonChange={onChange} value={value} mode="md" autocomplete="email" clearInput={true} ref={ref} type="email" inputmode="email" /> )} />`

**Comment by pfcodes** [comment]
Would love for there to be a native way to get an input ref.
