### ISSUE TITLE
Initialize form values

### ISSUE THREAD

**Issue by bobysf12** [bluebill1049/react-hook-form#27]
Hi! Thanks for making this awesome library!
I have a question, how do you initialize form values? Is there such a feature?

**Comment by bluebill1049** [comment]
Hi @bobysf12, 

we are using standard react input default value here.

https://codesandbox.io/s/l3mxpvmm9

More examples can be found here:
https://github.com/bluebill1049/react-hook-form/tree/master/examples

and react doc for defaultValue can be found here:
https://reactjs.org/docs/uncontrolled-components.html

cheers
bill

**Comment by bobysf12** [comment]
Thanks man!

**Comment by bluebill1049** [comment]
no worries man! if you find it useful please leave a star to support this repo 🙏if you already did, then thank you very much ❤️ happy coding feel free to ask questions here too :)
