### ISSUE TITLE
[Question] What to do with validation errors from Server? 

### ISSUE THREAD

**Issue by AskAlexSharov** [bluebill1049/react-hook-form#28]

**Comment by bluebill1049** [comment]
Hi @AskAlexSharov, 

I have an example for async validation at the field level, basically, you can send a request to the server and response with validation against it.

Async field:
https://codesandbox.io/s/m5pj55yj7x

or you can try Async validation on the submitting level:
https://codesandbox.io/s/xrjv48o0qp

let me know if those examples do help or not

cheers
bill

**Comment by AskAlexSharov** [comment]
Thank. And I see you added `setError`
