### ISSUE TITLE
[Feature request] Clear form

### ISSUE THREAD

**Issue by pandaiolo** [bluebill1049/react-hook-form#30]
**Is your feature request related to a problem? Please describe.**

I don't know how to cleanup the form when using this library, because it's uncontrolled. 

**Describe the solution you'd like**

Add a `clear` function in the hook returned object. Suggested API:
- `clear()` clear all fields of that form
- `clear('field1', 'field2')`clear only the specified fields
- TBD how to deal with initial values? should this revert to empty, or initial value? idk (and I do not use initial values so far in my use case)

**Describe alternatives you've considered**

- Add a ref myself on every input (which is a bit more complicated because of register function) and then imperatively set their value empty (or initial value) on each of them. 
- Make all input also controlled and use that to clear their value

Or maybe I'm missing something and this feature already exists? :)

**Comment by bluebill1049** [comment]
hey @pandaiolo,

there is a `reset()` method you can invoke to clear all fields and errors.

https://react-hook-form.now.sh/api

example here: https://codesandbox.io/s/jjm3wyqmjy

and for default and initial value: https://codesandbox.io/s/l3mxpvmm9

let me know if those fulfill your needs. 

cheers
bill

**Comment by pandaiolo** [comment]
Perfect, thank you! I just did not reload the docs in 2 days ;-)

(Which also means my Mac did not crash in more than two days, nice performance)

**Comment by bluebill1049** [comment]
haha 😍
