### ISSUE TITLE
[Question] Integration with React UI Frameworks

### ISSUE THREAD

**Issue by agustinl** [bluebill1049/react-hook-form#31]
Hi @bluebill1049 , first, congrats for you tool. Its very easy to use and usefull.

Its my first github issue, tell me if I do something wrong.

I try to use react-hook-form with [Evergreen UI](https://evergreen.segment.com/) but doesnt work with a components from this framework.

If i use [text input component](https://evergreen.segment.com/components/text-input), the validation doesnt show. But works ok when I change `<TextInput />` component for a simple `<input />` component.

I created a[ codesandbox](https://codesandbox.io/embed/00kzovjq6v) example to see the case better.

Thansk for you time!,
✌️

**Comment by bluebill1049** [comment]
Hey @agustinl,

You are doing fine mate :) Thanks for opening an issue ❤️ 

you just have to change `ref` to `innerRef` for Evergreen UI :) I did a quick test and its working for me. 

I think `<TextInput />` expose `innerRef` to forward `ref` same as material-ui.

cheers
bill

**Comment by agustinl** [comment]
Amazing!,
works perfect.

Thanks for the prompt response!

regards,
✌️
