### ISSUE TITLE
[Question] Arrayfields data object

### ISSUE THREAD

**Issue by Nikoflash** [bluebill1049/react-hook-form#33]
Hi, don't know if this is right place for questions, but now I try :)

In my project I have a fields array of products and I want the data to come out something like this:

```
products: [ 
  {
    name: "iPhone",
    description: "Overpriced hyped smart phone"
  },
  {
    name: "Huawei",
    description: "Chinese spying tool"
  }
]
```

But from looking at the fieldsArray example can only seem to get:

```
{
  products.name["iPhone", "Hauwei"]
  products.description["Overpriced hyped smart phone", "Chinese spying tool"]
}
```

I know, I'm doing something wrong, but is it possible to get what I want, by just writing the input name in a certain manner?

Best regards Nikolas

**Comment by bluebill1049** [comment]
hey, 

is this a possible solution?

```
{
  name: ["iPhone", "Hauwei"]
  description: ["Overpriced hyped smart phone", "Chinese spying tool"]
}
```

and during submiting `handleSubmit`
```
const onSumbit = (data) => {
  data.name.map((phoneName, i) => {
    return {
      name: phoneName,
      description: data.description[i],  
    }   
  })
}
```

**Comment by Nikoflash** [comment]
Thanks for a quick answer :)

I thought about a solution like that, but that would require all fields to aways contain data, to know how to pair them.

Think I'll go for something like:

```
products[0].name: "Iphone"
products[0].description: "Overpriced hyped smart phone"
products[1].name: "Hauwei"
products[1].description: "Chinese spying tool"
```

And then serialize the data on submit.
