### ISSUE TITLE
Custom Input validation

### ISSUE THREAD

**Issue by AlleyShairu** [bluebill1049/react-hook-form#34]
Hello, I can't seem to figure out why the validation doesn't work on custom inputs like Select2.

I have created a [fork](https://codesandbox.io/s/react-hook-form-custom-input-o48wk) of your custom input example, which already registers the select input, so I just added the required validation, now I expect that the **reactSelect** value will be available when the `onSubmit` function is triggered, but it's missing from data.

![Screenshot_2019-05-24_11-55-42](https://user-images.githubusercontent.com/6375481/58309026-8231da00-7e1c-11e9-8338-6a4241b2fcf2.png)

My understanding is that required validation will make sure all inputs values are available when the `onSubmit` function is triggered. Maybe I am wrong? **I also can't seem to make other validation rules work for custom input**.

How would you go about solving this? `setError` maybe?

and **Thank you** for creating this.

**Comment by bluebill1049** [comment]
Hey @AlleyShairu,

Is this what you after?

<img width="1361" alt="Screen Shot 2019-05-24 at 6 06 46 pm" src="https://user-images.githubusercontent.com/10513364/58312532-d2299480-7e4e-11e9-94fe-a0d9e2856019.png">

for a required field, you need to do `register({ required: true })`

let me know if this makes sense?

cheers
bill

**Comment by bluebill1049** [comment]
looks like react-select return empty array when nothing is selected, I may need to patch to fix required validation.

**Comment by AlleyShairu** [comment]
@bluebill1049 Take the below component as an example mentioned in the [codepen](https://codesandbox.io/s/react-hook-form-custom-input-oqriu)

```
<Select
  className="reactSelect"
  name="filters"
  placeholder="Filters"
  value={values.selectedOption}
  options={options}
  onChange={handleMultiChange}
  ref={e => register({ name: "reactSelect", required: true })}
/>
```
I have added the `register({ name: "reactSelect", required: true })`

Now what would happen if I submit the form without interacting with this input? 

- If it's submitting the form I should see the `reactSelect` value in the data object, even if it's the empty array.
- Or it shouldn't let me submit the form and populates the error object.

This is what I am getting after clicking the submit button without interacting with the input.

![Screenshot_2019-05-24_14-45-08](https://user-images.githubusercontent.com/6375481/58319546-6685fe00-7e33-11e9-8aaa-7f5add8764d5.png)

I am getting the same behavior with other components like react datepicker.

Thanks for spending your time on this.

**Comment by bluebill1049** [comment]
Thanks for the issue report, I will sort out ASAP.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-custom-input-dyh9q

try this one, let me know if make sense.

**Comment by AlleyShairu** [comment]
It does, tested with react-datepicker too.

So now to make the validation work on custom input, we should use the second parameter for rules like (_required_ or _validate_) in `register` function.

Thanks a lot for your hard work.

**Comment by bluebill1049** [comment]
yea :) that's correct. I used to validate with react select because return value can be an empty array.
If you find the package useful please kindly leave a star to support, much appreciated. ❤️

**Comment by ethaneisenhard** [comment]
@alleyshairu could you share that example with the react-date-picker?? that would be awesome

**Comment by alleyshairu** [comment]
@ethaneisenhard 
https://codesandbox.io/s/stoic-kirch-6oq7p
I just created this for you.

Basically, maintain the state of your custom input like you usually do, but also register the input so that the react-form-hook can know about it. You usually do it like
```
React.useEffect(() => {
	register({ name: "date" }, { required: true });
}, []);
```

and then whenever the input value change you use the react-form-hook **setValue** to assign the value to the input you registered. Now, this value will be available onSubmit.

```
<DatePicker
	isClearable
	selected={date}
	onChange={val => {
	setDate(val);
	setValue("date", val); // Here we are setting the value for the registered input.
	}}
/> 
```

Hope this was helpful.

**Comment by bluebill1049** [comment]
thanks a lot @alleyshairu for sharing with us!

**Comment by iamdevlinph** [comment]
For some reason when doing the custom register with `<FormContext />` the `methods.handleSubmit` does not fire.

The parent component which contains the form
```javascript
const Page: React.FunctionComponent = () => {
  const onSubmit = () => {
    console.log("clicked");
    methods.handleSubmit(data => {
      // this does not log
      console.log("data", data);
    });
  };

  return (
    <FormContext {...methods}>
      <form className="w-full">
        <FormSectionWithDate></FormSectionWithDate>
        <div className="py-6">
          <button onClick={onSubmit}>Save</button>
        </div>
      </form>
    </FormContext>
  );
};
```

The date component with the custom register
```javascript
const DatePicker: React.FunctionComponent = () => {
  const [startDate, setStartDate] = useState<any>(new Date());
  useEffect(() => {
    register({ name: "date" }, { required: true });
  }, []);

  return (
    <DatePicker
      // onChange={setStartDate}
      onChange={val => {
        setStartDate(val);
        setValue(name, val);
        console.log(val);
      }}
      value={startDate}
      // ref={() => register({ name: 'test' })}
    />
  );
};
```

**Comment by iamdevlinph** [comment]
Also tried with `[register]` but still no luck
```javascript
useEffect(() => {
    register({ name: "date" }, { required: true });
}, [register]);
```

**Comment by bluebill1049** [comment]
@iamdevlinph can you share a codesandbox for this and which version of RHF are you using?

**Comment by iamdevlinph** [comment]
I'm trying to create one but I always get a `cross-origin error` when I add the following code.
```
<form onSubmit={methods.handleSubmit(onSubmit)}>
```
I might just create a repository for it

**Comment by iamdevlinph** [comment]
I just realized the issue.

I was doing the wrong object for register
```js
useEffect(() => {
    register({ name }, { required });
}, []);
```
instead of 
```js
useEffect(() => {
    register({ name, required });
}, []);
```

🤦‍♂️🤦‍♂️

**Comment by bluebill1049** [comment]
@iamdevlinph all good. show me the error that you got if you have sometime too :)

**Comment by iamdevlinph** [comment]
I see. I understood my issue now.

With this syntax
```js
useEffect(() => {
    register({ name, required });
}, []);
```
the `required` is treated as a form field that's why the `methods.handleSubmit` triggers even though there are empty required fields.

While in this syntax (which is correct)
```js
useEffect(() => {
    register({ name}, {required});
}, []);
```
the `required` is the actual **required option** and that's why when I submit the form it doesn't trigger anything because there are empty required fields.

----

This is just a user error so I'm not sure if this can be prevented in the library.

**Comment by bluebill1049** [comment]
all good @iamdevlinph thanks for let us know too 👍 

next major version, we are simplify the API a bit. hopefully make your guys' life easier too.

**Comment by iamdevlinph** [comment]
It's quite simple enough. Just some bad eyesight 😅

**Comment by bluebill1049** [comment]
@iamdevlinph if you find it useful in the future, Please consider leave us a star too 🙏

**Comment by einatnielsen** [comment]
@bluebill1049 
I am using you example of custom input (I can't use ref) with minor changes:
1. I changed the select to be required and add validate like you suggested
        required: true,
        validate: value => {
          // need to validate if it is undefined or empty array
          return Array.isArray(value) ? value.length > 0 : !!value;
        }
2. I am using `formState.isValid' to determine the submit button's style

but it doesn't work smoothly - the style changes only after clicking the button

https://codesandbox.io/s/react-hook-form-custom-input-3zk4t

**Comment by iamdevlinph** [comment]
Please note that `formState.isValid` will only change automatically with `onChange` and `onBlur` modes. With the default `onSubmit` it will only validated on form submission

https://react-hook-form.com/api#formState

**Comment by iamdevlinph** [comment]
Hmm. I tried with onChange but the isValid didn't change. I think there's an issue on how the value of the select is handled.

**Comment by iamdevlinph** [comment]
You'll need to manually run `triggerValidation` for custom registered fields.

https://codesandbox.io/s/react-hook-form-custom-input-u20bh

>Note: If you want the custom registered input to trigger a re-render during its value update, then you should give a type to your registered input.

https://react-hook-form.com/api#register under custom register

**Comment by bluebill1049** [comment]
thanks @iamdevlinph 🙏 or `setValue('name', 'value', true)`

**Comment by einatnielsen** [comment]
Thank you @iamdevlinph and @bluebill1049 ! :-)

**Comment by antonbehaeghe** [comment]
> thanks @iamdevlinph 🙏 or `setValue('name', 'value', true)`

Hey, what exactly does this third param 'true' mean? Is it rerendering or enforcing a valid input?

I was having some trouble removing errors on input and neither setting a type in the register or manually triggering validation was working, but this is :)

**Comment by bluebill1049** [comment]
@antonbehaeghe check the doc, it's for trigger validation after set value: https://react-hook-form.com/api#setValue

**Comment by Zykhatslover** [comment]
Thank's @iamdevlinph  and @bluebill1049 .

Just a quick note : to refresh the component on `setValue`, it now has to be written this way : `setValue('name', 'value', { shouldValidate: true })`

**Comment by bluebill1049** [comment]
@Zykhatslover that's correct, so it will trigger the validation.

**Comment by hungdev** [comment]
> @ethaneisenhard
> https://codesandbox.io/s/stoic-kirch-6oq7p
> I just created this for you.
> 
> Basically, maintain the state of your custom input like you usually do, but also register the input so that the react-form-hook can know about it. You usually do it like
> 
> ```
> React.useEffect(() => {
> 	register({ name: "date" }, { required: true });
> }, []);
> ```
> 
> and then whenever the input value change you use the react-form-hook **setValue** to assign the value to the input you registered. Now, this value will be available onSubmit.
> 
> ```
> <DatePicker
> 	isClearable
> 	selected={date}
> 	onChange={val => {
> 	setDate(val);
> 	setValue("date", val); // Here we are setting the value for the registered input.
> 	}}
> /> 
> ```
> 
> Hope this was helpful.

Thank for your example. But the error still appears after choosing value. How to clear error?
@bluebill1049

**Comment by bluebill1049** [comment]
@hungdev use `shouldValidate` flag (check the doc)

**Comment by hungdev** [comment]
> @hungdev use `shouldValidate` flag (check the doc)

Thank for your reply. I used some validation libraries. I really like your lib. and like your enthusiasm for support <3

**Comment by bluebill1049** [comment]
no worries @hungdev so glad to hear that.
