### ISSUE TITLE
Can I use react-hook-form with custom input

### ISSUE THREAD

**Issue by chenka** [bluebill1049/react-hook-form#37]
It's work with native input like `<input>` but it didn't work If I create custom input from `styled-components`

Here's an example:
https://codesandbox.io/embed/nervous-sammet-5ioiz

or there's other solution to pass `props` to input?

**Comment by bluebill1049** [comment]
yea, you can mate  https://codesandbox.io/s/72j69vnk1x

**Comment by chenka** [comment]
got it, thanks man

**Comment by bluebill1049** [comment]
please leave a star if you find it useful to support this repo 🙏
