### ISSUE TITLE
setValue api cannot set radio button value  

### ISSUE THREAD

**Issue by ilovedesert001** [bluebill1049/react-hook-form#38]
setValue api cannot set radio button value  

https://codesandbox.io/s/react-hook-form-set-inputselect-value-9zlsy

**Comment by bluebill1049** [comment]
thanks for reporting :) https://codesandbox.io/s/react-hook-form-set-inputselect-value-c46ly

i have patched the issue

**Comment by bluebill1049** [comment]
https://github.com/bluebill1049/react-hook-form/releases/tag/3.8.1
