### ISSUE TITLE
ReactStrap Input error

### ISSUE THREAD

**Issue by viniciustodesco** [bluebill1049/react-hook-form#39]
I using input from reactstrap and doesn't work.
in registerIntoFieldsRef just got undefined in elementRef.type and elementRef.value.

import { Input} from 'reactstrap'
`  
                  <Input
                    type="text"
                    name="catalogName"
                    value={inputChange.catalogName}
                    onChange={handleInputChange}
                    placeholder="Nome"
                    ref={register({ required: true, name: 'catalogName' })}
                  />
          `
![Screen Shot 2019-05-29 at 08 51 16](https://user-images.githubusercontent.com/3026984/58555078-f5f22f00-81ee-11e9-906e-002504eb818b.png)

**Comment by bluebill1049** [comment]
hey,

try this 

```
import { Input} from 'reactstrap'

<Input type="text" name="catalogName" value={inputChange.catalogName} onChange={handleInputChange} placeholder="Nome" innerRef={register({ required: true })} />
```

by the way, you don't need the name in the `register` :) 

let me know how you go

**Comment by bluebill1049** [comment]
also, refer to this example if you want

https://codesandbox.io/s/72j69vnk1x

I have used material-ui input there

**Comment by bluebill1049** [comment]
Please check this example which have ReactStrap example now

https://codesandbox.io/s/72j69vnk1x

**Comment by bluebill1049** [comment]
i am going to close this issue if you dont mind :) you can look the example above, if still have question fee free to re-open it :)

**Comment by u007** [comment]
didnt work now

**Comment by jprosevear** [comment]
path.split is not a function is the error I get as well

**Comment by jprosevear** [comment]
See https://github.com/react-hook-form/react-hook-form/issues/4414

**Comment by jsette-bolttech** [comment]
examples provided are not working

**Comment by Joseph42A** [comment]
Not working!

**Comment by Moshyfawn** [comment]
Take a look at [this CSB](https://codesandbox.io/s/reactstrap-sandbox-forked-z2uxl?file=/src/index.js) for a working example.

Next time, please, consider creating a reproduction, confirming the RHF version you see the issue on and providing some information on the issue you're facing. "Not working" just doesn't help
