### ISSUE TITLE
Changing input clears all errors

### ISSUE THREAD

**Issue by GProst** [bluebill1049/react-hook-form#41]
**Describe the bug**
react-hook-form version: 3.8.2

If I create several inputs with simple `require: true` option then changing one input clears errors for all other inputs.

I believe it was caused by this change in `filterUndefinedErrors` util: https://github.com/bluebill1049/react-hook-form/commit/60f067faaa52f10e637d770799607d3e0bd7ab86#diff-214650c784ae501eee5389467af3c9a8
Since `value.isManual` is `undefined` for each value the `reduce` returns empty object

**To Reproduce**
1. Create 2 inputs with `ref={register({require:true})}`
2. Submit the form (two errors should be shown for each input)
3. Change value for one input
4. All input errors are cleared

**Expected behavior**
4. The error should be cleared only on the input which validation error was fixed

**Comment by bluebill1049** [comment]
Dame, I stuff it up... I will have to fix it ASAP :(

**Comment by bluebill1049** [comment]
thanks for the issue report, I have patched the bug :)

https://codesandbox.io/s/rwpz2jn6ln

**Comment by bluebill1049** [comment]
hey @GProst 

I think it's been resolved, let me know if it's good to close the issue :)

again, thanks very much for report the issue ❤️

cheers
bill

**Comment by GProst** [comment]
Seems working good, thank you! 👍
