### ISSUE TITLE
setValue() doesn't add field to formState.touched

### ISSUE THREAD

**Issue by durianjc** [bluebill1049/react-hook-form#43]
I'm using a date picker and it's not simple `<input />` so I manually add a hidden field for it:
`<input ref={register} name="date" type="hidden" defaultValue={dateStr} />`

And when user change/select a date, I use:
`setValue('date', dateStr);`

Everything works well, I can see that field's value changed by `watch()`. But in `formState.touched`, it doesn't contain `date`.

Is it a bug or I did something wrong? If it's a bug, is there a way to manually add field(s) to `formState.touched`?

**Comment by bluebill1049** [comment]
hey @durianjc 

Thanks for the reporting!

I will patch that bug over the weekend, it should register into `touched`.

by the way, you can `register` by useEffect too

```
useEffect(() => {
  reigster({ name: 'date' });
}, [])
```

so you don't have to create a hidden input.

**Comment by bluebill1049** [comment]
patched: https://github.com/bluebill1049/react-hook-form/releases/tag/3.8.4 👍

**Comment by durianjc** [comment]
> hey @durianjc
> 
> Thanks for the reporting!
> 
> I will patch that bug over the weekend, it should register into `touched`.
> 
> by the way, you can `register` by useEffect too
> 
> ```
> useEffect(() => {
>   reigster({ name: 'date' });
> }, [])
> ```
> 
> so you don't have to create a hidden input.

Thanks a lot for your quick response and patch, wow!

I also tried this approach before I used a hidden input, but there are problems with it, I posted another ticket: https://github.com/bluebill1049/react-hook-form/issues/44

**Comment by bluebill1049** [comment]
feel free to re-open this issue, if it is not resolved.
