### ISSUE TITLE
manually register({name: 'fieldname'}) doesn't include init/default value, and causes error when reset form

### ISSUE THREAD

**Issue by durianjc** [bluebill1049/react-hook-form#44]
If I register a field manually like this:
`useEffect(() => {
    register({ name: 'fieldname' });
}, []);`
or like this:
`<MyCustomInput
    ref={e => register({ name: 'fieldname' })} />`

I found 2 problems:
1. This field's value is not set (`undefined`) while other are set (checked by `watch()`).
2. When I `reset()` this form, it throws an error:
`TypeError: Object.values(...)[0].ref.closest is not a function`
<img width="511" alt="Screenshot at May 31 16-46-23" src="https://user-images.githubusercontent.com/47959733/58697438-b92b6100-83c3-11e9-9ae5-ed1bd93fa858.png">

---

Also, about the second approach (`ref={e => register(...)}`) I followed your example in documentation:
<img width="639" alt="Screenshot at May 31 16-49-38" src="https://user-images.githubusercontent.com/47959733/58697918-6e5e1900-83c4-11e9-9fb5-4863c387b3cf.png">

But I don't understand how it works, the `e` hasn't been used at all. In React official documentation, it doesn't mention there is an `e` in `ref` too. Could you help me to understand this?

**Comment by bluebill1049** [comment]
The example on website is bad, i have updated the page :) thanks 

looking at the first issue now

**Comment by bluebill1049** [comment]
I see the problem with `reset()` because all your input are custom input. there isn't any `input` on the page, hence reset failed to do the look up. For custom input like `DatePicker` or `React-select` you may have to reset the value in its component level. but i will patch the error throwing issue.

**Comment by bluebill1049** [comment]
check out this demo: https://codesandbox.io/s/72j69vnk1x

**Comment by bluebill1049** [comment]
patched this error throwing as well https://github.com/bluebill1049/react-hook-form/releases/tag/3.8.5

**Comment by bluebill1049** [comment]
I think for the custom element within the form you will have to do things like below.

```
const [dateValue, setDateValue] = useState('');

const resetForm = () => {
  setDateValue(''); // controlled custom component reset
  reset(); // react-hook-from reset
}

<form>
  <input ref="regsiter" name="text" />
  <DataPicker value={dateValue} handleChange={handleChange} />
  <button onClick={resetForm} type="button">Reset</button>
</form>
```

because react hook form wouldn't have access to the custom component but those one registered. hence you have to reset the value of custom component separately. let me know if this makes sense.

**Comment by bluebill1049** [comment]
going to close this issue now, unless you have other questions :) feel free to re-open if it doesn't make sense. cheers bill

**Comment by durianjc** [comment]
yes it works perfectly now, thanks a lot @bluebill1049 and your awesome component.

**Comment by bluebill1049** [comment]
Thank you 😝 if u find it useful plz kindly leave a star to support 🙏🏻🙏🏻❤️
