### ISSUE TITLE
[Question] `errors` type completion doesn't work well.

### ISSUE THREAD

**Issue by lightsound** [bluebill1049/react-hook-form#45]
Hi, thanks for the great form library.
I'm trying version 3.8.6 with typescript, but `errors` type completion doesn't work well. 

Demo
```ts
type FormData = {
  name: string;
};

const App: React.FC<SomeProps> = props => {
  const defaultValues: FormData = {
    name: props.name
  };
  const { register, handleSubmit, errors } = useForm<FormData>({
    mode: "onSubmit",
    defaultValues,
  });

  return (
    <form onSubmit={handleSubmit(data => console.log(data))}>
      <input
        name="name"
        ref={register({ required: "name is required." })}
      />
      {errors.name && errors.name.message}
      // Property 'name' does not exist on type 'typeof' ErrorMessages<FormData>

      <input type="submit" />
    </form>
  );
};
```

I read the source code and think this line is the cause.
https://github.com/bluebill1049/react-hook-form/blob/97952827cb90e145622e9f3c28087e91c3ff9f95/src/types.ts#L61

Do you think `| {}` is needed? Or, I'm glad you tell me the workaround.

**Comment by bluebill1049** [comment]
hmmm I am still learning typescript as well, maybe you can help here as well :) I am actually not so sure about this bit as well
`export type ErrorMessages<Data extends DataType> = { [Key in keyof Data]: Error } | {}; `

the reason I have added `{}` because the error's initial value is `{}`. will probably need to spend some time on this, or perhaps you have a good suggestion?
`<ErrorMessages<Data>>({})`

**Comment by bluebill1049** [comment]
This repo is still young, if you are expert in typescript please consider contributing to this repo, most of the types are the location in `types.ts` 🙏🏻

**Comment by bluebill1049** [comment]
I will remove this `{}` for now and add an ignore for now until I can figure out a better type for it :( need support from typescript expert on this

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/tender-bush-06v2d

thanks very much for report the issue @lightsound

**Comment by lightsound** [comment]
@bluebill1049 
I am still learning typescript too.
I tried to fix and opened PR (https://github.com/bluebill1049/react-hook-form/pull/47). 

Please check that. 🙇

**Comment by bluebill1049** [comment]
thank you! merged and published https://github.com/bluebill1049/react-hook-form/releases/tag/v3.8.9

**Comment by lightsound** [comment]
@bluebill1049 
Wow, thanks.
I'm glad to be a part of contributors.
If there is a chance again, I'll contribute. 😄

**Comment by bluebill1049** [comment]
going to close this since you solve it problem 😅
