### ISSUE TITLE
Cannot reproduce Performance Comparison. Re-render is occurred.

### ISSUE THREAD

**Issue by lightsound** [bluebill1049/react-hook-form#46]
I'm sorry in continuous posting.

I read Performance Comparison section on docs. I tried reproducing this with version 3.8.6 many times, but could not do. Is there an example of this code?
  
![image](https://user-images.githubusercontent.com/8220973/58759615-d5680300-8567-11e9-80db-84bf472ebcff.png)

**Comment by bluebill1049** [comment]
shit... looks like I break the code with last published

patched with `3.8.7`

https://codesandbox.io/s/priceless-williams-7btcl

**Comment by lightsound** [comment]
@bluebill1049 
Thank you for quick fix!
