### ISSUE TITLE
Despite setting to 'onSubmit', Input validation occurs on blur

### ISSUE THREAD

**Issue by hadiranjbar25** [bluebill1049/react-hook-form#48]
I have set validation mode to onSubmit (It is default value). But, validation occurs on input blur.
This is how I register my input:

```
 <input
        ref={register({ required: true })}
        name="password"
        type= "password"
      />
```
When leaving the input, required error appears on page.
I use V 3.8.9

**Comment by bluebill1049** [comment]
any chance you can give me the entire code?

the following example seems to be ok.

https://codesandbox.io/s/priceless-williams-7btcl

**Comment by bluebill1049** [comment]
do you mean after submit was clicked and the revalidation behavior? at the moment, revalidation is based on input change, but I am planning to introduce another prop to force revalidation to be a specific type.

**Comment by hadiranjbar25** [comment]
No, the form is pristine. I click on an input and then I click on the page. Consequently, validation fires and adds a required type validation to errors.

**Comment by bluebill1049** [comment]
hmmm its really weird, did you look the example link I shared? it worked there, can you share your code tho?

**Comment by hadiranjbar25** [comment]
Unfortunately I cannot share whole code. You right it works in your shared example. it's wired!

**Comment by hadiranjbar25** [comment]
I think I got the problem. I try to use it in a multi-step way. In every step I have a submit validation, when it validates on time, in next steps it fires validations onChange!

**Comment by bluebill1049** [comment]
Shouldn’t u break it into mutiple forms?

**Comment by hadiranjbar25** [comment]
Technically it's one form that every field of it is in one step.

**Comment by bluebill1049** [comment]
Then you probably shouldn’t submit the form when it’s not fully fulfilled, maybe have a button which take to the next step. And validate at the end.

**Comment by hadiranjbar25** [comment]
How can I call just validation and not submit?

**Comment by hadiranjbar25** [comment]
> Then you probably shouldn’t submit the form when it’s not fully fulfilled, maybe have a button which take to the next step. And validate at the end.

No I can't. In every step, user should provide valid information!

**Comment by bluebill1049** [comment]
I don't think your approach is going to work with how `react-hook-form` works, because validation will trigger perform via `submit` button which is an HTML standard.

I suggested if the from is big, you should break them into individual forms and collect them individually. I am working on a funnel which contains 40 plus steps (forms) and that's how we work.

feel free to provide your suggestion tho

**Comment by hadiranjbar25** [comment]
Great! I think there should be a validate function like what exist in 'rc-form'. It just validates current fields or the fields name that we provide as parameters.

**Comment by bluebill1049** [comment]
thanks for the sharing `rc-form` :)

After reviewing, I don't think that the direction `react-hook-form` should be heading, the whole point of making this custom hook is to make things simple by introducing less API if possible.

The last option on top of my head is only `register` input after previous steps pass. 

step A: <input ref={regster} />
step B: <input /> unitl step A pass  then <input ref={register} />

I think I have provided my suggestion to make it works, break it into multiple forms or register only when required.

**Comment by bluebill1049** [comment]
ok, I have a better solution may be is good for you.

```
<form>
  <input /> // step1

  {step2Valid && <><input /><input /></>} // step 2
  {step3Valid && <><input /><input /></>} // step 3
</form>
```

if you don't render step2 and step3 inputs, then validation won't kick in, start to render rest of steps by validating previous steps.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-validationfields-1xb91
