### ISSUE TITLE
Array inside form model

### ISSUE THREAD

**Issue by cabezonidas** [bluebill1049/react-hook-form#49]
Hi, I started using this plugin recently, and it's great. I have forms that their model contains arrays, so I need some sort of looping. I know that you do that, but you save the paths as keys and the form values end up something like this:
`{
 "title": "my form",
 "people[0].name": "peter",
 "people[1].name": "john"
}`

whereas the model is like below
`{
 "title": "my form",
 "people": [ { "name": "peter"}, { "name": "john" } ]  
}`

In my case I am using the `set` function from lodash to map the form object inside onSubmit to my business model.

Something like `set(newModel, 'people[0].name', 'peter')` works fine.

So, I was wondering if you could use in your api a function like "set" so you can assign complex paths a value, and then also gain the benefits of TS for the "errors" object, where you can access to errors.people[0].name. I think that as a result, your form data will reflect the business model which can be beneficial.

**Comment by bluebill1049** [comment]
Hi @cabezonidas 

Good point, the intend data format was to be something like

```
name: ['xxx', 'yyy'];
```

here is a working sandbox:
https://codesandbox.io/s/6j1760jkjk

maybe that will make your life bit easier to do a simple `reduce` function. 

in terms of transform data into the correct modal, I think it sounds like some thought of array fields data transform. I don't think I have a good idea to expose a simple API for that, keep some good thinking.

cheers
bill

**Comment by bluebill1049** [comment]
going to close this issue for now, until I have a proper solution for it :)

**Comment by cabezonidas** [comment]
Thanks @bluebill1049 

I guess either way requires some extra work map to the business model. Anyway, good stuff and thanks for your reply. Looking forward to the feature ;)
