### ISSUE TITLE
[Feature request] Yup or Joi as a object validation

### ISSUE THREAD

**Issue by afgallo** [bluebill1049/react-hook-form#5]
Hi @bluebill1049 you may want to consider a feature where libraries such as [yup](https://github.com/jquense/yup) or [joi](https://github.com/jeffbski/joi-browser) can be used to simplify complex validation scenarios. I've used this with [formik](https://jaredpalmer.com/formik/docs/guides/validation#validationschema) in the past and really enjoyed it.

Keep up with the good work, mate!

Cheers

**Comment by bluebill1049** [comment]
hey @afgallo, that's the next feature in my features log. i am probably only going to support yup for now, cause it's more popular.

usage probably just going to be as simple as:

`const { register } = useForm({ validationSchema: yourSchema });`

**Comment by bluebill1049** [comment]
hey @afgallo,

`"version": "0.4.0-beta.6",`

`https://codesandbox.io/s/928po918qr`

here is the working version. if you could do some testing would be great, i will do so. 

if everything works fine i will publish in the next minor version.

**Comment by bluebill1049** [comment]
https://github.com/bluebill1049/react-hook-form/releases/tag/v0.4.0

**Comment by sonhanguyen** [comment]
hey I found out about your library on echojs today and found it a refreshment having to deal with formik at work and not liking very much. Just want to chime in to give some feedback regarding to the validation API.

I think this library should not have to support a particular validation library. It's better to have an option that is simply a `validate` function (if result to a boolean) or `getErrors` (if result to errors, like `prop-types`). That way it's clear from the naming what is expected and people can just write a validation function even if they are not using a validation library, I'm sure Yup or Joi should provide a way to get a function out of a schema too.

**Comment by bluebill1049** [comment]
thanks for the feedback @sonhanguyen, I am still emphasis validation with `register` method from react hook form, but give other developers like @afgallo's freedom to use Yup or those schema validation libraries they refer. 

I personally prefer something like below:

```
import React from 'react'
import useForm from 'react-hook-form'

function App() {
  const { register, handleSubmit, errors } = useForm() // initialise the hook
  const onSubmit = (data) => { console.log(data) } // callback when validation pass
    
  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input name="firstname" ref={register} /> {/* register an input */}
      
      <input name="lastname" ref={register({ required: true })} /> {/* apply required validation */}
      {errors.lastname && 'Last name is required.'} {/* error message */}
      
      <input name="age" ref={register({ pattern: /\d+/ })} /> {/* apply pattern validation */}
      {errors.age && 'Please enter number for age.'} {/* error message */}
      
      <input type="submit" />
    </form>
  )
}
```

**Comment by sonhanguyen** [comment]
From my experience validation at field level is only good for providing quick visual feedback for simple mistakes. It falls short as soon as you need to validate something based on input from multiple fields. Even when it suffices, for anything domain related I prefer the validation logic to be centralized in a single validate function that takes the whole data object and returns a map.
```ts
type ValidationError = any
type Validator<T> = (_: Partial<T>) => PromiseLike<void | {[K in keyof T]?: ValidationError}>
```

**Comment by bluebill1049** [comment]
isn't that validation schema with yup? or any schema validation library

**Comment by sonhanguyen** [comment]
I don't use that library so if that is already the case I guess my remaining point is just the naming. If the only thing this library is concerned with is a function that takes input and returns errors then maybe just call the option `validate` or `validator` and document the expected output in the docs. Having some "schema" options and mentioning of a 3rd library gives the impression that only that library can be used.

**Comment by bluebill1049** [comment]
yea sure, validator probably make more sense, in terms of validation schema I have that documented under the website: https://react-hook-form.now.sh/api should be easy to expose to other validation library or even custom ones in the future.

**Comment by bluebill1049** [comment]
I am going to close this feature request now, it's in the lib now.
