### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by pabloibanezcom** [bluebill1049/react-hook-form#50]
Hi,

Great work doing this, I've been using it for form building in my app. However I'm having one important issue when running `npm run build` (the app was created with create-react-app). The issue is:

```
Failed to minify the code from this file:

        ./node_modules/react-hook-form/dist/index.es.js:9:44
```

I've tried updating react-scripts to v.2.0.0 but the problem remains. Any idea how to solve this?

**Comment by bluebill1049** [comment]
Hi,

thank for your kind words ❤
any chance of sharing your package.json, i can try it out myself :) 
thanks

**Comment by bluebill1049** [comment]
just a quick follow up, how are you doing with it?

**Comment by bluebill1049** [comment]
going to close this issue :) feel free to open if still an issue 👍
