### ISSUE TITLE
Works with PrimeReact's InputText ?

### ISSUE THREAD

**Issue by rbgfloripa** [bluebill1049/react-hook-form#51]
Hi,

First, sorry for my bad english :)

The register method does not work with PrimeReact components.
Do you have any way to use it correctly?
I have tried in many ways that I read in the documentation and on the forums. 
Nothing worked :(

Can you help me ?

Thanks

Rafael.

**Comment by bluebill1049** [comment]
hey,

I checked PrimeReact component source code, looks like they are not exposing `ref` at all. React Hook Form is not compatible with this UI library.  :( maybe consider using material ui or another ui library if you can, otherwise, I don't think I can do much about it :(

cheers
bill

**Comment by bluebill1049** [comment]
I am going to close this issue, but leave an example for you :)

https://codesandbox.io/s/72j69vnk1x

in case you decide to go with another library like material UI

**Comment by narroyog** [comment]
It's possible to wrap the primereact component within a react-hook-form <Controller /> component to get it registered on the form:  
[https://react-hook-form.com/advanced-usage/#ControlledmixedwithUncontrolledComponents](https://react-hook-form.com/advanced-usage/#ControlledmixedwithUncontrolledComponents)

**Comment by mertsincan** [comment]
Hi,

You can use react-hooks-form with PrimeReact;
https://primefaces.org/primereact/showcase/#/reacthookform

**Comment by bluebill1049** [comment]
thanks @mertsincan

**Comment by mertsincan** [comment]
@bluebill1049, Thank you very much for this great form library. I really enjoyed integrating PrimeReact library and React Hook Form.

**Comment by gokhantiknaz** [comment]
Hi,

I'm working with prime react  & react-hook form validation. 
But i couldnt get defaultvalues in useEffect. Or I cant set values from api in useEffect. what must i do for this? I'm using component inside components
MasterComponent
          childcomponent 1
          childcomponent 2

Master component includes two or more child component.  And my submit button is in master component.

Here is a sample for only load values from api.

https://codesandbox.io/s/angry-gagarin-ypb3d
