### ISSUE TITLE
Checkbox value

### ISSUE THREAD

**Issue by chiefcll** [bluebill1049/react-hook-form#52]
Hi,

I have a form with checkboxes in it with a value attribute set. 
```
               <input
                  name={`device-${num}`}
                  type='checkbox'
                  value={device.id}
                  ref={register}
                />
```

When I use getValues() - It returns an object with "device-1": true, "device-2": false rather than the device.id value.

Src:
https://github.com/bluebill1049/react-hook-form/blob/master/src/logic/getFieldValue.ts#L12

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

According to the spec - I'd like for the value to be the value set on the input box when it is checked. Something like checked ? value : false

**Comment by bluebill1049** [comment]
do you mean `defaultChecked`?
```
<input
   name={`device-${num}`}
  type='checkbox'
  defaultChecked={device.id}
  ref={register}
/>
```

**Comment by chiefcll** [comment]
No...

https://www.w3schools.com/jsref/prop_checkbox_defaultchecked.asp

That tells you if the box was `checked` by default. I want when you see that the element is checked, rather than returning true or false, you should check for a value attribute and return that if it is checked and false otherwise.

**Comment by bluebill1049** [comment]
oh.... oops I will patch that soon

**Comment by bluebill1049** [comment]
thanks for reporting :) patched this bug  👍 

react-hook-form@3.8.10

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/yj07z1639 

fixed and closing the issue.

**Comment by zernie** [comment]
@bluebill1049 I'm having the some problem when using getValues/watch(). Instead of array they return individual elements, eg `{'test[0]': false, 'test[1]':false}`


https://codesandbox.io/embed/react-hook-form-basic-qgkkp

**Comment by bluebill1049** [comment]
@zernie looks like that's a bug, you want to open a separate issue? I will follow it up

**Comment by zernie** [comment]
@bluebill1049 sure

**Comment by nageshwari17** [comment]
@bluebill1049 how it will work with controlled component with material UI ?

**Comment by bluebill1049** [comment]
> @bluebill1049 how it will work with controlled component with material UI ?

https://react-hook-form.com/api#Controller

here is a CSB:
https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

**Comment by Allakazan** [comment]
Hello i'm having some problems with checkboxes on react-hook-form
When i use **defaultChecked** the form won't reset the fields (using  `reset()`), will just keep the default.
When i take out the **defaultChecked** and keep only the **register** function the fields will reset but won't have a default value.
What should i do ?
