### ISSUE TITLE
[Feature Request] Trigger validation programatically

### ISSUE THREAD

**Issue by mitchellsimoens** [bluebill1049/react-hook-form#53]
**Is your feature request related to a problem? Please describe.**

If a user doesn't enter a value, the validation doesn't happen until submission. However, if I am in a wizard (a single form has multiple steps), I want to prevent someone from continuing to the next step. If someone clicks the next button, the fields are not checked so the user cannot be prevented.

**Describe the solution you'd like**

I'd like a function returned by `useForm` to trigger a validation of the fields. Bonus points to also accept `string | string[]` fields to only validate given fields.

**Describe alternatives you've considered**

Currently I have to also use `getValues` but this doesn't show the error message then:

```typescript
validate: (): boolean => !errors.title && Boolean(getValues().title),
```

I'd like to do:

```typescript
validate: (): boolean => validate('title')
```

And the `errors` object then have an error (if the field is invalid) so that my form can show the error also. From what I've seen in the code, the validation is only internal and no way for me to get to it easily and the different `modes` don't handle if the field was never focused.

**Comment by bluebill1049** [comment]
I like this `validate()` function, will be working on that. 

in terms of validated specific fields, there is another users reported the same concern as well. I think it makes sense to specify fields to validate at `useForm` level.

**Comment by bluebill1049** [comment]
I have quickly build a beta version, maybe you can help to test, I will do my own after work.

```
useForm({ validationFields: string[] })

validate() => boolean
```

**Comment by bluebill1049** [comment]
react-hook-form@3.9.0-beta.1

**Comment by bluebill1049** [comment]
`validateField()`: validate individual fields
https://codesandbox.io/s/react-hook-form-validatefield-w1g0m

`validationFields`: restrict fields with validation
https://codesandbox.io/s/react-hook-form-validationfields-1xb91

still in the beta will publish soon

**Comment by mitchellsimoens** [comment]
Thank you @bluebill1049. The `trigger` function is particularly what I want.

**Comment by mitchellsimoens** [comment]
And fyi, I have used `3.9.0-beta.7` for testing and the `trigger` function is what is working for me.

**Comment by bluebill1049** [comment]
cool, i will publish soon

**Comment by bluebill1049** [comment]
published: https://github.com/bluebill1049/react-hook-form/releases/tag/v3.9.0 🤗

**Comment by barry4dev** [comment]
This great - just wondering why you didn’t stick with validate()?

**Comment by bluebill1049** [comment]
because  `register` already have `validate` method, i dont want it to be confused with both.
`regsiter({ validate: (data) => data === 'something' });`

that's why `trigger` popped in my head to trigger validation.

**Comment by mitchellsimoens** [comment]
Thanks for your work on this so fast and your work on this module @bluebill1049

**Comment by bluebill1049** [comment]
no worries @mitchellsimoens, please consider starring the repo to support and share around the community :) 🙏

**Comment by bluebill1049** [comment]
hey @mitchellsimoens,

Quick question here, you happy for `trigger` to be able to validate onlyafter submit button pressed?

https://github.com/bluebill1049/react-hook-form/pull/60

cheers
bill

**Comment by mitchellsimoens** [comment]
@bluebill1049 as long as I can programmatically trigger a validation, I'm happy. Even if it's not technically a public api, so long as I have access to mess around a bit.

**Comment by bluebill1049** [comment]
FYI: I have changed the name of the method from 'trigger' to 'trigger validation'. but won't affect your current version: 3.10.2

https://react-hook-form.com/api
