### ISSUE TITLE
IE11 support ?

### ISSUE THREAD

**Issue by opeah** [bluebill1049/react-hook-form#56]
Hi,

Thanks for the great library. I've been using it for all my projects, but it does not work on IE11.
Can you add support for this one ?

I got ```Syntax error``` in **useForm/index.es.js** (line 9)

If you have IE11, you can try it here https://comptaplan-dev.netlify.com

Thank you

**Comment by bluebill1049** [comment]
hey @opeah,

Lovely to hear you find it useful! 

I don't have PC around me, but I will look into that. I think it may be just a build config, will let you know :)

cheers
bill

**Comment by bluebill1049** [comment]
Can you show me a screenshot of the code error? 
line 9 is a `.reduce` function, I doubt it will crash at 11

**Comment by opeah** [comment]
![Screenshot 2019-06-06 at 11 03 13](https://user-images.githubusercontent.com/31569566/59020748-e7d58b80-884a-11e9-9959-1e4d1fb6b269.png)
![Screenshot 2019-06-06 at 11 02 52](https://user-images.githubusercontent.com/31569566/59020749-e86e2200-884a-11e9-8521-01200d0f92e5.png)

**Comment by bluebill1049** [comment]
Thanks for the screenshot, I am afraid it doesn't help a lot. hmmm, I will try to get a PC in the office.

**Comment by bluebill1049** [comment]
![image](https://user-images.githubusercontent.com/10513364/59081890-cf8d6b80-8933-11e9-8fbf-84e9791dca92.png)
tried on my college's IE11, I didn't see the error for some reason

**Comment by opeah** [comment]
Refresh the page and you'll see it
It does not work because the image is not loaded

**Comment by bluebill1049** [comment]
page was fully loaded when I was testing (as shown in the loading bar and icon), not sure about the image been blur. I will take a look again next week

**Comment by bluebill1049** [comment]
sorry for the delay reply @opeah, it's too hard to get my hands on a PC these days... but can you try to add this?

`import 'babel-polyfill'; `

see if that solve the problem of IE 11

**Comment by KB1RMA** [comment]
I'm running into this as well. It looks like you're not transpiling arrow functions. Are you open to changing the compatible target for transpilation?

**Comment by bluebill1049** [comment]
@KB1RMA i am using rollup for the build, do you have a fix? please send a PR if you do.

**Comment by bluebill1049** [comment]
can you guys try this?

`import 'babel-polyfill'` at your app.js

and install this version `react-hook-form@3.11.4-beta.2`

**Comment by opeah** [comment]
works for me thanks @bluebill1049

**Comment by bluebill1049** [comment]
@opeah is it ok if I build an IE version just for you guys? cause with `babel` it blows up the package size from `3.8kb` to `5.1kb` personally I still prefer to keep this package as light as possible. 😄

**Comment by bluebill1049** [comment]
going to close this, for now, if you need IE support, I am happy to build an IE version and you just have to `import 'babel-polyfill'

**Comment by KB1RMA** [comment]
Thanks for looking into this. For the moment, transpiling the module myself with babel solves my issue (and including polyfills of course). So if you don't plan to support IE (which I don't blame you for!) then no biggie. Perhaps a section in the documentation reflecting supported browsers might be a nice addition though.

**Comment by bluebill1049** [comment]
@KB1RMA can you show me what you did? i will write this on the FAQ page, many thanks

**Comment by bluebill1049** [comment]
going to close this, @KB1RMA if you could drop some instruction here then I can update the documentation. many thanks, bill

**Comment by davidspiess** [comment]
Hi @bluebill1049, i took a short look in your codebase and i think there isn't that much to adjust to support IE11 too!

```js
// Object.entries is not supported
Object.entries(errors);
// New
Object.keys(errors).map(key => errors[key]);

// Array.includes is not supported
fieldName.includes(name);
// New
fieldName.indexOf(name) !== -1;
```
With these changes the only requirement for library consumers, which are worried about IE11, is adding a Promise polyfill. This is handled similar in Formik (https://github.com/jaredpalmer/formik/issues/870).

If you plan to support IE11, i can take a deeper look and provide a pull request too!

**Comment by bluebill1049** [comment]
Hi @davidspiess, thanks for the comment. I believe @KB1RMA have fixed the issue on his end:

> Thanks for looking into this. For the moment, transpiling the module myself with babel solves my issue (and including polyfills of course). So if you don't plan to support IE (which I don't blame you for!) then no biggie. Perhaps a section in the documentation reflecting supported browsers might be a nice addition though.

would be nice to know how and documented on the website.

I would love to support IE 11, but I think it's going to blow up the size of the package. if you have a solution without adding extra dependency that would be great.

cheers
bill

**Comment by davidspiess** [comment]
Thanks for your quick response @bluebill1049!
The `@babel/polyfill` solution adds a lot of unnecessary polyfills to my package size when in the end the only required changes in your codebase would be the one i stated above.
I would not suggest to add any polyfills to your library but leave it to the library consumer to add them.
Currently i think the following polyfills are needed to support IE11:
```
Array.prototype.includes
Object.prototype.values
Promise
```

Regardless of that a notice about the required polyfills on your website would be great:
Here an example how react-pose displays it on their website: https://popmotion.io/pose/api/faqs/#faqs-browser-support?

**Comment by bluebill1049** [comment]
oh nice thanks @davidspiess for the link, I will update accordingly :)

**Comment by bluebill1049** [comment]
<img width="628" alt="Screen Shot 2019-07-02 at 8 04 44 pm" src="https://user-images.githubusercontent.com/10513364/60504327-bd210a80-9d04-11e9-9375-5b4bf6c292c4.png">

thanks @davidspiess updated

**Comment by davidspiess** [comment]
I think you mistakenly copied too much from the react-pose text 😄

**Comment by bluebill1049** [comment]
dame it, guess I am a bit too tired after work :( thank you tho~!

**Comment by davidspiess** [comment]
Time to take a break 🍻 🎉

**Comment by michaelbirchler** [comment]
@davidspiess thanks for the info regarding the polyfills. But only adding the polyfills without transpiling won't work. There are some arrow functions in the dist code, like this:

`var isCheckBoxInput = (type) => type === 'checkbox';`

and arrow functions are unfortunately not supported on Internet Explorer https://caniuse.com/#feat=arrow-functions

**Comment by davidspiess** [comment]
@michaelbirchler yes transpiling with babel or typescript is still required.

**Comment by bluebill1049** [comment]
@davidspiess should I include that message in the website under IE 11 support:

> transpile with babel or typescript is still required

**Comment by davidspiess** [comment]
@bluebill1049 I think it would be better changing `"target": "es2017"` to `"target": "es5"` in `tsconfig.json`. Not sure if this has any implications on existing users though.

**Comment by michaelbirchler** [comment]
@davidspiess If I use `"target": "es5" inside `tsconfig.json` I get an application error with the react app: 
> Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. 

Do you know if there is an easy workaround, maybe in adjusting the `compilerOptions`? 🙇

**Comment by bluebill1049** [comment]
@davidspiess I tried that as well, I got some error last time. :(

**Comment by michaelbirchler** [comment]
@bluebill1049 I got the Invariant Violation error 

> Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.

because I've used `yarn link` to link to a local copy of _react-hook-forms_ and this caused to include [two copies from react]( https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react). To fix this I had to use `yarn link react` (to point back to the app directory) and `yarn link react-dom` inside the local copy of the `react-hook-form` module.

**Comment by bluebill1049** [comment]
thanks @michaelbirchler for the info

**Comment by catamphetamine** [comment]
My fix for the IE 11 bug:

Webpack config

```js

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules[\/\\](?!(react-hook-form)[\/\\])/,
        use: [{
          loader: 'babel-loader'
        }]
      },
```

**Comment by bluebill1049** [comment]
thanks for sharing @catamphetamine 

we do export ie11 compatible version now

`import useForm from 'react-hook-form/dist/react-hook-form.ie11'`

**Comment by ecwyne** [comment]
@bluebill1049 Thank you so much for the separate ie11 build!

However, TS typings aren't working for me. How should I obtain TS typings for the ie11 build?

**Comment by ecwyne** [comment]
This has seemed to work in the meantime

```
declare module 'react-hook-form/dist/react-hook-form.ie11' {
    export { default } from 'react-hook-form';
    export * from 'react-hook-form';
}
```

**Comment by tomaskallup** [comment]
@bluebill1049 I've noticed that the ie11 doesn't support `Proxy` ([mdn link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#Browser_compatibility)), which is used in the ie build, thus it doesn't work.

**Comment by bluebill1049** [comment]
hey, @tomaskallup I do a check against support for proxy :)

**Comment by frank-martinez-27** [comment]
I have a react app that needed to support IE11 and also had the issue with the Proxy, this is how I got it to work. I did `npm install --save proxy-polyfill` and on my app.js file I added `import 'proxy-polyfill/proxy.min.js';` at the top and then this function 
```
if (!window.Proxy) {
  const proxyPolyfill = ProxyPolyfillBuilder();
  window.Proxy = new proxyPolyfill();
}
```
Hope this helps someone in the future.

**Comment by ccnokes** [comment]
@bluebill1049 
> I do a check against support for proxy :)
By that do you mean that polyfilling `Proxy` is unnecessary? Or do we still need the polyfill for it to work properly?

**Comment by bluebill1049** [comment]
@ccnokes i haven't test the IE 11 build for a while, but last time someone made a commit to include all the polyfills.

**Comment by marksy** [comment]
> This has seemed to work in the meantime
> 
> ```
> declare module 'react-hook-form/dist/react-hook-form.ie11' {
>     export { default } from 'react-hook-form';
>     export * from 'react-hook-form';
> }
> ```

i dont understand how to use this, can someone explain how i do? i seems to only work if i put it in the node_modules/react-hook-form/dist folder :(

**Comment by kotarella1110** [comment]
@marksy You only have to create `react-hook-form.ie11.d.ts`.

```ts
declare module 'react-hook-form/dist/react-hook-form.ie11' {
    export * from 'react-hook-form';
}
```

codesandbox: https://codesandbox.io/s/react-hook-form-issue-56-v7z4c

**Comment by jonhaddow** [comment]
Alternatively (if using webpack) add this to the config:
```javascript
resolve: {
  alias: {
    "react-hook-form": "react-hook-form/dist/react-hook-form.ie11"
  }
}
```
to always use the IE compatable version of react-hook-form

**Comment by ryansully** [comment]
In 6.0.0+ the webpack resolution should use `'react-hook-form': 'react-hook-form/dist/index.ie11` instead:
```
resolve: {
  alias: {
    "react-hook-form": "react-hook-form/dist/index.ie11"
  }
}
```

**Comment by maxenz** [comment]
@ryansully saved my day bro

**Comment by microgold** [comment]
saved me too

**Comment by Ubiquitous23** [comment]
This still doesn't work for me. importing 
```js
import { useForm } from 'react-hook-form/dist/index.ie11';
```

Allows app to load in IE11 but as soon as I go to a component that uses react-hook-form it throws this error in both IE 11 and chrome.

```
Uncaught TypeError: Incompatible receiver, Set required
    at src.b3e59893.js:1314
    at T.<anonymous> (src.b3e59893.js:1418)
    at new T (src.b3e59893.js:1356)
    at exports.useForm (src.b3e59893.js:1782)
    at j (src.b3e59893.js:1806)
    at ua (src.b3e59893.js:583)
    at Ro (src.b3e59893.js:583)
    at Lu (src.b3e59893.js:583)
    at Ru (src.b3e59893.js:583)
    at Cu (src.b3e59893.js:583)
```

**Comment by Ubiquitous23** [comment]
> This still doesn't work for me. importing
> 
> ```js
> import { useForm } from 'react-hook-form/dist/index.ie11';
> ```
> 
> Allows app to load in IE11 but as soon as I go to a component that uses react-hook-form it throws this error in both IE 11 and chrome.
> 
> ```
> Uncaught TypeError: Incompatible receiver, Set required
>     at src.b3e59893.js:1314
>     at T.<anonymous> (src.b3e59893.js:1418)
>     at new T (src.b3e59893.js:1356)
>     at exports.useForm (src.b3e59893.js:1782)
>     at j (src.b3e59893.js:1806)
>     at ua (src.b3e59893.js:583)
>     at Ro (src.b3e59893.js:583)
>     at Lu (src.b3e59893.js:583)
>     at Ru (src.b3e59893.js:583)
>     at Cu (src.b3e59893.js:583)
> ```

FYI I fixed this by removing @babel/polyfill and following the instructions to use core-js and regenerator-runtime instead

**Comment by nataliaroque77** [comment]
@Ubiquitous23 
 All my app works - but not forms, I followed instructions for use core-js and regenerator-runtime.  Did you added something specific in order to make work react-hook-forms ie11
