### ISSUE TITLE
Register by name breaks validation

### ISSUE THREAD

**Issue by breytex** [bluebill1049/react-hook-form#61]
**Describe the bug**
I am trying to connect a SemanticUI controlled component to the hook-form lib.
I am using
```
  useEffect(() => {
    register({ name: "somename" }, { required: true })
  }, [])

const onChange = (e) => {
    setValue("somename", e.target.value)
  }
```
to connect it.

However, the validation behaves in a weird way: 
- When trying to fill out the input field in a valid way and submit, it works
- When trying to first submit a not valid form, fill it out afterwards and submit, it still gives an validation error 

**To Reproduce**
Minimal example: 
https://codesandbox.io/s/rough-pine-p8ypz?fontsize=14

![2019-06-07 11 53 48](https://user-images.githubusercontent.com/4541640/59096589-76b1d900-891b-11e9-852a-29a25089ec98.gif)

**Expected behavior**
Validation should work after:
- submitting an invalid form
- input valid data
- submitting again

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by bluebill1049** [comment]
hey @breytex,

Thanks for the detailed issue reporting :)

because you registered that input manually instead of 

`<input ref={regsiter} />`

so react hook form will not have the reference with the input `ref` when you start to type in the `input`, It wouldn't re-validate itself.

with `setError` you can set error and clear manually

```
const handleChange = (e) => {
  if (e.target.value) {
    setError('test');
  }
}
<input onChange={handleChange} />
```

**Comment by bluebill1049** [comment]
hey @breytex 

just a quick follow up on this issue, how u doing with it?

cheers
bill

**Comment by bluebill1049** [comment]
going to close this issue, for now, feel free to reopen if you still have question 👍
