### ISSUE TITLE
Issue with async submit

### ISSUE THREAD

**Issue by kabriel** [bluebill1049/react-hook-form#63]
**Describe the bug**
if you provide an async submit handler, the isSubmitting will not be updated correctly

**To Reproduce**
1. add async submit handler that takes 2sec to finish
2. notice the form state will not show isSubmitting for those 2 seconds

**Expected behavior**
isSubmitting should be true while submit handler is pending

**Additional context**
To work around this issue (not claiming this is a fix because i do not know the code well) I patched my version with the following:

https://github.com/bluebill1049/react-hook-form/blob/2bf73dddbb043963e4f61b799b7b1f884b6acad7/src/index.ts#L344

before:
```
    if (isEmptyObject(fieldErrors)) {
      callback(combineFieldValues(fieldValues), e);
    } else {
      errorsRef.current = fieldErrors;
      reRenderForm({});
    }
```

after:
```
    if (isEmptyObject(fieldErrors)) {
      await callback(combineFieldValues(fieldValues), e);
      reRenderForm({});
    } else {
      errorsRef.current = fieldErrors;
      reRenderForm({});
    }
```

this awaits on the promise returned by the onSubmit handler (seems this is required if you intend to support async submit handlers as the docs claim) and then re-renders the form so all form state can update

**Comment by bluebill1049** [comment]
thanks, @kabriel for the detailed bug report :) you want to submit a PR for this?

your solution is correct

```
   if (isEmptyObject(fieldErrors)) {
      await callback(combineFieldValues(fieldValues), e);
    } else {
      errorsRef.current = fieldErrors;
    }
      reRenderForm({});
```

**Comment by bluebill1049** [comment]
thanks very much, @kabriel https://github.com/bluebill1049/react-hook-form/releases/tag/v3.10.3

**Comment by einatnielsen** [comment]
Hi @kabriel @bluebill1049 
I am experiencing this issue: formState.isSubmitting is not true when submit is async
I am using version 4.3.0

**Comment by bluebill1049** [comment]
can you provide a codesandbox @einatnielsen ?

**Comment by polRk** [comment]
```
  const onLogin: OnSubmit<LoginFormData> = async values => {
    return firebase
      .auth()
      .signInWithEmailAndPassword(values.email, values.password)
  }

```

formState.isSubmitting is not true

**Comment by bluebill1049** [comment]
make sure you are reading formState before render.

https://react-hook-form.com/api#formState

Important: formState is wrapped with Proxy to improve render performance, so make you have invoke/read it beforerender in order to enable the state update.

that's probably the root cause.

**Comment by polRk** [comment]
<img width="709" alt="Снимок экрана 2020-01-25 в 11 11 56 PM" src="https://user-images.githubusercontent.com/39828645/73126807-1796f680-3fc8-11ea-9aec-734f3e16a0db.png">

**Comment by bluebill1049** [comment]
can you produce a codesandbox so I can reproduce this issue?

**Comment by polRk** [comment]
No, I did not work with codesandbox and I am sure, it will take long time. I think, you can reproduce this bug using `setTimeout` wrapped in `Promise`

**Comment by peterrattew** [comment]
If you want help with an issue then you need to put in the time and setup an example that demonstrates it. This is an open source project and the people on here don't owe you anything.

**Comment by bluebill1049** [comment]
Thank you @peterrattew 🙏 i hope more people like yourself who is willing to help each others. 🙇

**Comment by PraveenPeri** [comment]
I have a similar need where I am trying to do some post-processing after the submission is complete for which, I was trying to rely on isSubmitting. Essentially, my approach is to do nothing while isSubmitting is true and invoke post-processing once it is false. But I can't to get it work meaning, isSubmitting never seems to be true. The onSubmit handler is async. 
Here's the sandbox - https://codesandbox.io/s/pedantic-star-4412m?file=/src/App.js
