### ISSUE TITLE
FUNDING.yml has parsing errors

### ISSUE THREAD

**Issue by markmssd** [bluebill1049/react-hook-form#65]
Heads up! Just to let you know that your button `Sponsor` throws this error message:

<img width="451" alt="Screen Shot 2019-06-08 at 1 07 42 PM" src="https://user-images.githubusercontent.com/5899024/59150255-851cf500-89ee-11e9-91f2-1d9d463f7093.png">

**Comment by bluebill1049** [comment]
LOL thank you ❤️
