### ISSUE TITLE
Validate component with State.

### ISSUE THREAD

**Issue by ejuo** [bluebill1049/react-hook-form#69]
**Describe the bug**
If the validated component has the State, then the input is blocked.
```javascript
// Form
<form onSubmit={handleSubmit(onSubmit)}>
            <div>
              <Input
                name="phone"
                error={errors.phone && errors.phone.message}
                forwardedRef={register({ 
                  validate: (value) => {
                    if (value.length < 4)
                      return CONSTANTS.INPUT_ERROR_PHRASE.EMPTY_FIELD
                    if (value.length >= 4 && value.length < 18)
                      return CONSTANTS.INPUT_ERROR_PHRASE.INVALID_FIELD
                  }}
                )}
              />
            </div>
</form>
```
```javascript
// Input
interface IState {
  value: string;
}
export class Input extends Component<InputProps, IState> {
  onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value  = this.setMask(event.target.value);
    this.setState({ value });
    this.props.onChange && this.props.onChange(event);
  }
  render () {
    return (
        <input
          name={name}
          value={this.state.value}
          ref={forwardedRef}
        />
    );
  }
}
```
I suspect because of the [re-render](https://github.com/bluebill1049/react-hook-form/blob/7c9d54e367d74559033a4f29841c4b1f3e7a821e/src/index.ts#L179) form, the event on onChange is not calls.

 - Browser Chrome, Safari, Edge
in Firefox not reproduced.

**Comment by bluebill1049** [comment]
hey @ejuo 

Do you try to do masking?

the following example may help.
https://codesandbox.io/s/387z7njwzp

**Comment by ejuo** [comment]
@bluebill1049, thanks for the response.
I'm using [react-imask](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask) for mask. Most likely it stores the state. 
Are there any other options?

**Comment by bluebill1049** [comment]
Yea I think maybe u can use setValue. Check out the api page and give it a try.

**Comment by ejuo** [comment]
There is the problem, that using `setValue` with `onChange` not check only mounted component on submit. Eg. `required` field case.

**Comment by bluebill1049** [comment]
you can use `triggerValidation` after value change

**Comment by ejuo** [comment]
Made[ codesandbox example](https://codesandbox.io/s/react-hook-form-custom-input-63d84).
`triggerValidation` means that I cannot native `handleSubmit`? It's more convenient to use that others inputs uses ref.
And I'm interested in the question, what are the consequences if disable [`input` event](https://github.com/bluebill1049/react-hook-form/blob/5b6cd10601439ea2643db71b2a914a556af38de3/src/logic/attachEventListeners.ts#L15) for 'onSubmit' and 'onBlur' modes for `useForm`?

**Comment by bluebill1049** [comment]
what do you mean disable `onSubmit` and `onBlur` for `useForm`?

**Comment by ejuo** [comment]
Not add listener for input event.

**Comment by bluebill1049** [comment]
I think this is working version.

https://codesandbox.io/s/react-hook-form-custom-input-k87mt

**Comment by ejuo** [comment]
Thanks for example. I would like to get rid of duplicate validates and make uniform error management. But it's works, thanks!

> what do you mean disable onSubmit and onBlur for useForm?

If we need validate only on `blur` event, why we must add `input` listener? Or I don't understand why we need validation modes for the `useForm`.

**Comment by bluebill1049** [comment]
you should be able to abstract those `validate` methods into own files if there is reusable value.

I made this package for everyone's need in the community, in case they want validation to fire at 'onChange', 'onBlur' or 'onSubmit'. For me at work, we just use the default which is onSubmit.

**Comment by ejuo** [comment]
> I made this package for everyone's need in the community, in case they want validation to fire at 'onChange', 'onBlur' or 'onSubmit'. For me at work, we just use the default which is onSubmit.

I understand. In my case I use `onSubmit` and `onBlur` too. It means, that inputs go validate by `blur` event? 
Why we need call validate fuction by `input` event? 
I try comment [this line](https://github.com/bluebill1049/react-hook-form/blob/5b6cd10601439ea2643db71b2a914a556af38de3/src/logic/attachEventListeners.ts#L15). Validation continue works. But I do not see the whole picture, maybe something is missing. This allowed me use `ref` realisation with my custom inputs.

**Comment by bluebill1049** [comment]
you are right if you set the validation to be onBlur then input event can be avoided. feel free to send a PR to correct this.

**Comment by bluebill1049** [comment]
going to close this as well, next release will have the #74 merge :)
