### ISSUE TITLE
After first submit with error values, the form can't be submitted again

### ISSUE THREAD

**Issue by faltysad** [bluebill1049/react-hook-form#70]
**Describe the bug**
I am using react-hook-form with nextjs. After I submit my form for the first time (with intended errors) it works fine. But when I remove the errors (edit the values of inputs) I can't submit the form again hence the errors don't disappear and the whole form doesn't react to submitting.
I have to refresh the page.

**Expected behavior**
Expected behavior would be that the errors disappear and the form gets submitted again.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.80

**Additional context**

**Comment by faltysad** [comment]
```
...
function SignUpForm() {
    const { register, handleSubmit, errors } = useForm();

    const onSubmit = data => { dispatch(SignUpUser(data.email, data.password)) };


    return (
        <>
            <h3>Create an account</h3>
            <form onSubmit={handleSubmit(onSubmit)}>
                <input type="email" name="email" ref={register({ required: true })} />
                <input type="password" name="password" ref={register({ required: true })} />
                <input type="submit" value="register" />
            </form>
             {(errors.email || errors.password) && <p>All of the fields are required</p>}
            <Link href="/signin"><a>Already have an account? Sign in</a></Link>
        </>
    )
}
...
```

**Comment by faltysad** [comment]
![image](https://user-images.githubusercontent.com/15239773/59211620-8e55bf80-8bb0-11e9-8848-8cbd696867bb.png)

**Comment by bluebill1049** [comment]
that's strange... thanks for the detailed issue report. i will do a test with your code

**Comment by bluebill1049** [comment]
weird seems works for me https://codesandbox.io/s/blissful-fog-76c4g

**Comment by faltysad** [comment]
Thanks for the reply @bluebill1049 , but I still can't get it to work.
Do you have any ideas what I might be doing wrong? The issue still persists for me.
I can even find in the current ref that the value is okay, the only issue is that for some reason, `react-hook-form` still thinks that there are issues with the field and I cant get it to submit.
![image](https://user-images.githubusercontent.com/15239773/59248611-3ad08980-8c23-11e9-857e-e7dc2aca0eea.png)

**Comment by bluebill1049** [comment]
which version are you running?

**Comment by faltysad** [comment]
Sure, I tried to setup next.js demo on code sandbox with the exact same code and it works.
https://9zyyq.sse.codesandbox.io
So the problem must be on my side.. I am running react hook form 3.9.0

**Comment by faltysad** [comment]
Can confirm that version update of `react-hook-form` to latest fixed this for me. Thanks for your help @bluebill1049 !

**Comment by bluebill1049** [comment]
oh cool! no worries at all. happy coding :) feedback welcome

**Comment by bluebill1049** [comment]
you happy to close this issue? 👍

**Comment by faltysad** [comment]
Sure, great work with `reac-hook-form` btw!

**Comment by jordansoltman** [comment]
For anyone else that find themselves with this problem, I was experiencing the same thing and after spending *far* too much time trying to figure out what was wrong, I realized that onSubmit was calling the error callback (not the main callback). The errors are preventing it from firing again (which is a bit of a gotcha if you are doing just server-side validation).

**Comment by bluebill1049** [comment]
> For anyone else that find themselves with this problem, I was experiencing the same thing and after spending _far_ too much time trying to figure out what was wrong, I realized that onSubmit was calling the error callback (not the main callback). The errors are preventing it from firing again (which is a bit of a gotcha if you are doing just server-side validation).

if you are setting `errors` manually while not assigned to any input, you as the user will need to manually clear that error.

https://react-hook-form.com/api#errors

> An error that is not associated with an input field will be persisted until cleared with clearError. 

This is by design, so we have consistent rules against error with input or server side.

**Comment by bluebill1049** [comment]
that's valid use case :) @vcarel 👍
