### ISSUE TITLE
setValue() doesn't dirty the form

### ISSUE THREAD

**Issue by kabriel** [bluebill1049/react-hook-form#72]
**Describe the bug**
I use setValue to update a field 

**To Reproduce**
Create a form with an input and use a button to update it via setValue or triggerValidation (which calls setValue)

You can see an example here:
https://codesandbox.io/s/react-hook-form-trigger-validation-1dn2h
notice when you press the submit button, the fields update, the form is still not dirty

**Expected behavior**
I would expect changing a form value via setValue would dirty the form (otherwise we can't update the form from complex ui controls)

I don't have a fix for this yet, it looks more complex than a few lines.

**Comment by kabriel** [comment]
there are use-cases where setValue is currently being called (such as in register) that should not update dirty, so I'm trying this solution out for now:

https://github.com/kabriel/react-hook-form/commit/9c50dd9567d3866bfb483bfde507230a415be792

would love to know how you see this working and how you envision this.

**Comment by bluebill1049** [comment]
I think `register` shouldn't trigger `dirty`, but if you call it manually it probably should dirty the field.

**Comment by bluebill1049** [comment]
I should be able to fix this issue or feel free to send a PR too 🥃

**Comment by bluebill1049** [comment]
https://github.com/bluebill1049/react-hook-form/commit/1e12ef8968b38ed04a1101d3bcba56f58887f2b8

**Comment by bluebill1049** [comment]
published, I will write the relase note when i get to work. need to get off my bed now lol

**Comment by bluebill1049** [comment]
https://github.com/bluebill1049/react-hook-form/releases/tag/v3.10.5

**Comment by bluebill1049** [comment]
hey @kabriel, 
I am going to close this issue now :) also this repo is young, please consider supporting by star the repo and share around the community 🙏

**Comment by allicanseenow** [comment]
@bluebill1049 Should we allow devs to control whether to control `dirty` when we call `setValue`?
The purpose of "dirty" is mainly to check if user has entered a new value to a field or not, not to check if devs programmatically change that value, imo.

Let's say in the use case I fetch data from a server, and then I set that data as the default value of a field. In this case, `defaultValue` doesn't work because I don't have data before calling the API so I have to use `setValue` to manually change the value of the field. Using `value` instead of `defaultValue` is out of the question as controlled components are not optimal.

**Comment by bluebill1049** [comment]
> Let's say in the use case I fetch data from a server, and then I set that data as the default value of a field. In this case, defaultValue doesn't work because I don't have data before calling the API so I have to use setValue to manually change the value of the field. Using value instead of defaultValue is out of the question as controlled components are not optimal.

can you use `reset({})`?

**Comment by allicanseenow** [comment]
Thanks for the response. However, I think `reset` will clear the value of all fields, which is not my intention. Besides, even if I can still retain the value of each field after calling `reset`, `formState.dirty` will still have its value transitioning from 'false' -> 'true' -> 'false'. This might cause some strange behaviors on UX if I rely on `dirty` to show or hide other components.

**Comment by bluebill1049** [comment]
> Thanks for the response. However, I think reset will clear the value of all fields, which is not my intention.

i believe you can `reset({ mutlipleValues })` // you can use getValues and reset the value plus the new value. in terms of reset `dirty` value maybe we can introduce second args specific for reset particular `formState`

**Comment by bluebill1049** [comment]
> Let's say in the use case I fetch data from a server, and then I set that data as the default value of a field. In this case, defaultValue doesn't work because I don't have data before calling the API so I have to use setValue to manually change the value of the field. Using value instead of defaultValue is out of the question as controlled components are not optimal.

also maybe consider this to be leave outside of hook form, useState probably is better to deal with that.

**Comment by allicanseenow** [comment]
I tried to use `reset` but it doesn't seem to work with a TextField Select from MUI, which `setValue` seems to work with. This is the sample of my code:
````
<Controller
      name={name}
      control={control}
      as={
        <TextField select name={name}>
          {children}
        </TextField>
      }
      // Must have defaultValue to be '' so that react-hooks-form's "setValue()" works
      defaultValue={''}
      onChange={([a]) => a.target.value}
/>
````
`setValue` works if I set `defaultValue` as an empty string instead of skipping it. However, `reset` doesn't work with it. It does work with other uncontrolled fields though.

**Comment by bluebill1049** [comment]
> I tried to use `reset` but it doesn't seem to work with a TextField Select from MUI, which `setValue` seems to work with. This is the sample of my code:
> 
> ```
> <Controller
>       name={name}
>       control={control}
>       as={
>         <TextField select name={name}>
>           {children}
>         </TextField>
>       }
>       // Must have defaultValue to be '' so that react-hooks-form's "setValue()" works
>       defaultValue={''}
>       onChange={([a]) => a.target.value}
> />
> ```
> 
> `setValue` works if I set `defaultValue` as an empty string instead of skipping it. However, `reset` doesn't work with it. It does work with other uncontrolled fields though.

can you try to set a defaultValue at useForm level for reset() with controller?

https://react-hook-form.com/api#reset

**Comment by allicanseenow** [comment]
I got the same result. There are 2 types of input components from MUI I use, which are `<TextField/>` and `<TextField select/>`. I have tried setting the `defaultValue` at the component level (<TextField defaultValue={}/>), at useForm and no `defaultValue`. The behavior is:

- It works normally for all use cases with normal <TextField/>
- defaultValues (set at either component level or useForm) works for <TextField select/>. However, it does not work with `reset`. `setValue` doesn't work unless I initially set `defaultValue` as an empty string, which is an odd behavior to me.

**Comment by bluebill1049** [comment]
> I got the same result. There are 2 types of input components from MUI I use, which are `<TextField/>` and `<TextField select/>`. I have tried setting the `defaultValue` at the component level (), at useForm and no `defaultValue`. The behavior is:

can you send a codesandbox on the one?

**Comment by bluebill1049** [comment]
@allicanseenow maybe this feature will be useful to your issue: https://github.com/react-hook-form/react-hook-form/pull/1139

**Comment by allicanseenow** [comment]
Oh, thanks for the quick work. I will check that out soon.

**Comment by abhishekkumar1-kiwi** [comment]
> there are use-cases where setValue is currently being called (such as in register) that should not update dirty, so I'm trying this solution out for now:
> 
> https://github.com/kabriel/react-hook-form/commit/9c50dd9567d3866bfb483bfde507230a415be792
> 
> would love to know how you see this working and how you envision this.

Link not working. Can you please check this

**Comment by DeanRae** [comment]
I am a little confused. Was the fix to this issue removed in later releases because setValue still doesn't dirty the form for me.

**Comment by bluebill1049** [comment]
> I am a little confused. Was the fix to this issue removed in later releases because setValue still doesn't dirty the form for me.

Can you provide more context, please? codesandobx and which version.

**Comment by DeanRae** [comment]
> > I am a little confused. Was the fix to this issue removed in later releases because setValue still doesn't dirty the form for me.
> 
> Can you provide more context, please? codesandobx and which version.

Sorry for the wait. [Here's the sandbox](https://codesandbox.io/s/setvalue-no-dirty-p2eu5). I believe I am using the latest release: react-hook-form@6.0.2. When you change the value of the TextField using the Select component, only Select registers as dirty. Am I possibly using the react-hook-form components wrong? 

Thanks for the help :)

**Comment by bluebill1049** [comment]
@DeanRae by default we are not dirty the field now: https://react-hook-form.com/api#setValue 

`setValue('xxx', 'test', { shouldDirty: true })`

**Comment by DeanRae** [comment]
> { shouldDirty: true }

Awesome, thank you!

**Comment by abhisekp-impeller** [comment]
https://react-hook-form.com/api/useform/setvalue

Doesn't work with Form Context as per the Codesanbox

**Comment by nageshwari17** [comment]
Hi, Guys. Can I able set {shouldDirty: true} based on condition. As [https://codesandbox.io/s/ecstatic-frog-c857t?file=/src/App.tsx](https://codesandbox.io/s/ecstatic-frog-c857t?file=/src/App.tsx) this example . Intitialy I have firstName as 'test' , when I click set hello btn, field become dirty . and again I re-set intial value to field but field still dirty . Is any way that when I re-set intial value dirty get false.

**Comment by brettdewoody** [comment]
Seeing the same as @abhisekp-impeller - that `setValue` within a `useFormContext` does not cause the field to become dirty even when using the `shouldDirty` option in `setValue`.  

Is this expected?

**Comment by sadek-rayhan** [comment]
Same as @abhisekp-impeller . Not working with `useFormContext`. Is there any solution for this?

**Comment by NettaB** [comment]
Seeing the same thing here. @brettdewoody did you find a good workaround for this?

**Comment by thiagozulato** [comment]
@NettaB you can force this behavior using this option ```{ shouldDirty: true }```.

```javascript
setValue('type', value, { shouldDirty: true });
```
