### ISSUE TITLE
[REQ]: Nested Object model

### ISSUE THREAD

**Issue by stramel** [bluebill1049/react-hook-form#73]
**Is your feature request related to a problem? Please describe.**
It is difficult to work with nested object models in the form with the current setup. This feels slightly related to the array model (#49 and #33). For example, when working with models like so:

```
{
	name: {
		first: 'John',
		last: 'Doe',
	}
}
```

**Describe the solution you'd like**
It would be nice on the form to be able to use syntax like `<input name="name.first">` and `<input name="name.last">` to specify a nested object model.

**Describe alternatives you've considered**
Another option that I have seen, is a custom component that is considered a "grouping" that would associate the inputs with the nested object. Something like:

```
<Grouping context="name">
	<input name="first">
	<input name="last">
</Grouping>
```

**Comment by bluebill1049** [comment]
I think this would be a nice option to start with: 

`<input name="name.first"> and <input name="name.last">`  

I will think about a better approach around that, in the meantime, you will probably have to map the value.

**Comment by bluebill1049** [comment]
hey @stramel and @cabezonidas,

What about this idea?

<input name="{ "name": "first" }"> and <input name="{ "name": "first" }">

I can easily use `JSON.parse` instead of writing some complicated logic to parse that string.

**Comment by bluebill1049** [comment]
what's your thoughts @barry4dev ?

**Comment by stramel** [comment]
@bluebill1049 	I like this approach and think it is easy to comprehend from the developer's point-of-view.

**Comment by bluebill1049** [comment]
cool, I start working on the feature already, keen to see @barry4dev 's opinions too 👍

**Comment by cabezonidas** [comment]
> hey @stramel and @cabezonidas,
> 
> What about this idea?
> 
> `<input name="name[0].firstName"> and <input name="name[0].lastName">`
> 
> and produce
> 
> `name: [ { firstName: '', lastName: '' } ]`
> 
> `<input name="name.firstName"> and <input name="name.lastName">`
> 
> and produce
> 
> `name: { firstName: '', lastName: '' }`

Are you talking about the second option? If so, it'd be a good feature cause name attr is consistent with the path of the value. I would expect if my object is like `{ name: { first.name: '', last.name: '' }` to write html in the form like  `<input name="name['first.name']">`

What I'm saying is that it needs to follow json accessing rules for also names that contain dots as part of their name, as well as other special chars. It would be great to produce same business model. I think `get` and `set` functions from lodash are what you need for this. Even for arrays, they work great.

The first option, though, I think helps solve this specific case, and still, you have to do a mapping on the path of the object, and the dev will have to know this rule for nested json/arrays. In my opinion, having the exact path in the name attr will solve all cases.

**Comment by bluebill1049** [comment]
@cabezonidas I want to support both 
`<input name="name[0].firstName"> and <input name="name[0].lastName">`
`<input name="name.firstName"> and <input name="name.lastName">`

**Comment by bluebill1049** [comment]
hey @stramel,

I built a beta version if you are happy to have a try. if everything goes well should be able to release it this week.

`npm i react-hook-form@3.11.0-beta.1`

cheers
bill

**Comment by stramel** [comment]
@bluebill1049 	Thank you for the quick work! 

I tested all these scenarios (Checked worked):

- [x] Array Syntax `firstName[0]`
- [ ] Nested Array Syntax `person[0]numbers[0]`
- [x] Object Syntax `name.first`
- [ ] Nested Object Syntax `person.name.first`
- [x] Array of Objects Syntax `person[0].firstName`
- [ ] Array of Objects with Nested Object `person[0].name.first`


I'm not sure if you plan to support Nested Syntax.

**Comment by bluebill1049** [comment]
Probably required a lot more work to make it work for a deep nested object. right now it only supports one level. 

maybe we just do progressive here, let's support 1 level first and then looking for a better solution for deep nested. any thoughts?

**Comment by bluebill1049** [comment]
wondering if there is any package out there, can convert this `person[0].numbers[0]` to object 🤔

**Comment by bluebill1049** [comment]
anyway I will publish what I got soon and working on the nested object after that 👍

**Comment by bluebill1049** [comment]
ok, this version should tick everything now:

react-hook-form@3.11.0-beta.5

**Comment by stramel** [comment]
Dang, you beat me to it. It's a bit sloppy but you can take a look. https://gist.github.com/stramel/3514f9f7611ebaf87ce55b7e6357c0fb

I will take a look at the updated version

**Comment by stramel** [comment]
I tested all these scenarios (Checked worked):

- [x] Array Syntax `firstName[0]`
- [x] Nested Array Syntax `person[0]numbers[0]`
- [x] Object Syntax `name.first`
- [x] Nested Object Syntax `person.name.first`
- [x] Array of Objects Syntax `person[0].firstName`
- [x] Array of Objects with Nested Object `person[0].name.first`

@bluebill1049 	All scenarios appear to work now with `react-hook-form@3.11.0-beta.7`. Thank you for addressing this quickly!

**Comment by bluebill1049** [comment]
ha not gonna lie, I am stealing code from lodash. you can take a look the last commit.

**Comment by bluebill1049** [comment]
Thanks very much for your support @stramel won't mind to put you as a contributor as you help on testing and even contribute code 👍 (if you don't mind)

**Comment by cabezonidas** [comment]
Thanks! I'll give it a go soon. Maybe you'd want as well `unset` from lodash for dynamic forms. It's like `delete key`, (I saw that in the code) but you can send a complex path, like an element of a nested array, same as `get` and `set`. Anyway, I'll check it out soon. Good work, thank you!

**Comment by stramel** [comment]
@bluebill1049 I would be happy to help out where I can. I'm planning on fully implementing this in one of my work's projects. I'm sure it will be a good test of this library.

Thanks again! I'm going to close this issue with the release of 3.11.0.

**Comment by bluebill1049** [comment]
<img width="576" alt="Screen Shot 2019-06-14 at 7 28 02 am" src="https://user-images.githubusercontent.com/10513364/59468683-0274b980-8e76-11e9-8cf9-d323d4dc7d44.png">

@stramel thank you for contributing and your help on this issue :) much appreciated

**Comment by barry4dev** [comment]
@bluebill1049 @stramel  So sorry I missed this conversation (I gotta reduce my notification list a bit).  I think the idea is fascinating and likely helpful.  I'll try it out in 3.11 and see how it goes!

**Comment by bluebill1049** [comment]
all good @barry4dev ❤️

**Comment by The-Code-Monkey** [comment]
How would we make this dynamic in the terms of similarly how reduxform and other libraries have their fieldarray that lets the user dynamically add another index to the array.

**Comment by bluebill1049** [comment]
@The-Code-Monkey check out the example folder for array fields. i think it's much simpler than react-form IMHO

**Comment by dextervip** [comment]
Does this implementation supports yup schema validation with nested objetcs in array? I am trying to code it but I am not able to get errors on nested objects.

**Comment by bluebill1049** [comment]
@dextervip it should tho, can you supply a codesandbox which is not working for you?

**Comment by simonv3** [comment]
Could this be implemented for `watch` too? Currently that spits out: 

```
 {"items[0].quantity": "12", "items[1].quantity": "12", "items[2].quantity": "5", "items[3].quantity": "25" }
```

But handleSubmit does handle it properly.

**Comment by bluebill1049** [comment]
@simonv3 try to `watch('items')`

**Comment by simonv3** [comment]
Oh sweet, that works. Thanks! Is there a reason it doesn't unpack the entire changed object with just `watch()`?

**Comment by bluebill1049** [comment]
I will consider introducing a `nest` prop as the second argument for `watch` which will return you data as nested object.

**Comment by AlexJangam** [comment]
I have a reverse scenario, where my field names are dynamic(user defined) and allows .(dot), and 'react hook form' is considering as a nested object. I want to consider it as plain key. Is there a attribute or option that I can mention to form that its not nested?
<input name='first.second' value=""/>
its not {first : { second: ''}} but {'first.second': ''}

**Comment by bluebill1049** [comment]
@AlexJangam we are using dot to detect nested object, it's difficult or impossible to differentiate.

**Comment by tafelito** [comment]
@bluebill1049 is it possible to access a nested field from an object with a dynamic key

If I have 

```json
{
   "dsndknskdnsd": {
      "name": "",
      "lastName": ""
   }
}
```

because just by using dsndknskdnsd.name in the name does not seem to work, and neither the watch

**Comment by bluebill1049** [comment]
> ```json
> fields
> ```

watch('fields') should work.

**Comment by tafelito** [comment]
That works but then you gett all fields not just 1

What about the name of the input?

**Comment by parker789** [comment]
I have a unique scenario here that I'd like to be able to create a nested object with an ID as its key, like so `name="obj1.obj2.255"`, but the 255 is generating an array where the 255 index item is set to the field's value.

Any thoughts?

**Comment by Deboracgs** [comment]
For errors would suggest anything? I tried in this way, but when have nested objects, doesn't works. For example, address.country, the error doesn't appears

```
import { FC, Fragment } from 'react'
import { FieldErrors, FieldValues, UseFormRegister, ValidationRule } from 'react-hook-form'
import { useIntl } from 'react-intl'
import { InputTextStyled } from './index.styled'

type InputTextComponentProps = {
    placeholder: string;
    value: string | number | undefined;
    name: string;
    register: UseFormRegister<FieldValues>,
    required?: string | ValidationRule<boolean>;
    errors?: FieldErrors;
    disabled?: boolean
}

const InputTextComponent: FC<InputTextComponentProps> = ({
    placeholder, value, name, register, required, errors, disabled
}) => {
    const intl = useIntl()
    const hasError = errors && errors[name] ? true : false
    return (
        <Fragment>
            <label htmlFor={`input-${name}`} className="form-label">{intl.formatMessage({ id: placeholder })}</label>
            <InputTextStyled
                className={`form-control ${hasError ? 'is-invalid' : ''}`}
                placeholder={intl.formatMessage({ id: placeholder })}
                defaultValue={value}
                {...register(name, { required })}
                id={`input-${name}`}
                disabled={disabled || false}
            />
            <div className="invalid-feedback">
                {hasError && `${intl.formatMessage({ id: placeholder })} ${intl.formatMessage({ id: "validation.is-required" })}`}
            </div>
        </Fragment>
    )
}

export { InputTextComponent as InputText }
```

**Comment by NuteIla** [comment]
I'm also having problems with my nested form.
If my form has {people:[]} where people takes in {name:string, country:string} and I can keep "Add a new Person".

If I register a field to 
<input register={register(people[idx].name)}>, it keeps overwriting people[idx].name to undefine, even tho I handled default on first load. 
Errors have some issues as above.

**Comment by bluebill1049** [comment]
> I'm also having problems with my nested form.
> If my form has {people:[]} where people takes in {name:string, country:string} and I can keep "Add a new Person".
> 
> If I register a field to `<input register={register(people[idx].name)}>`, it keeps overwriting people[idx].name to undefine, even tho I handled default on first load.
> Error validation also has the same issues as above thread

can you provide a codesandbox?

**Comment by NuteIla** [comment]
> > I'm also having problems with my nested form.
> > If my form has {people:[]} where people takes in {name:string, country:string} and I can keep "Add a new Person".
> > If I register a field to `<input register={register(people[idx].name)}>`, it keeps overwriting people[idx].name to undefine, even tho I handled default on first load.
> > Error validation also has the same issues as above thread
> 
> can you provide a codesandbox?

Apologies, I noticed the problem is not with library but with useSession. Thanks for offering quick help!

**Comment by bluebill1049** [comment]
all good @NuteIla 👍

**Comment by NuteIla** [comment]
> all good @NuteIla 👍

Hi Bluebill, it's me again. I managed to replicate the problem with the following sandbox.
When <input is toggled between disabled boolean states, the form values will be set to undefined. 

https://codesandbox.io/s/spring-dawn-vyhh5?file=/src/App.tsx

Thank you so much for your help!

**Comment by bluebill1049** [comment]
you want readOnly not disabled @NuteIla

**Comment by NuteIla** [comment]
> you want readOnly not disabled @NuteIla

Changing to readonly fixes the problem. thanks blue

**Comment by jonnathanc765** [comment]
> @The-Code-Monkey check out the example folder for array fields. i think it's much simpler than react-form IMHO https://codesandbox.io/s/6j1760jkjk

I used this solution with version 7.12.0 and some updates, and Works perfectly!!

**Comment by rosanzheng** [comment]
@[Deboracgs](https://github.com/Deboracgs) I know it's a little bit late, but I have found a small workaround, since I just encountered the same issue.

It may not be the prettiest solution, but it did it for me for now at least. I am writing a UI-component library, which is why this solution might seem a little bit "overdone" but I belive, that you will be able to apply it to your case!

Here's my helper function:

```
const findNestedError = (
  errors: FieldErrors,
  formKeyArray: string[]
): FieldError => {
  let i = 0;
  let tmpError = errors[formKeyArray[i]];
  while (i < formKeyArray.length - 1) {
    i += 1;
    if (tmpError) {
      tmpError = tmpError[formKeyArray[i]];
    }
  }
  return tmpError;
};
```

The iteration does not look super pretty, but I was not able to think of a more beautiful way to do this. If you come across a way to iterate through an array and using the computed interim value from the previous iteration, please let me know!

My idea behind this, is that you can access your nested error object like this: `error[firstJey][nestedKey1][nestedKey2]` and so on.
