### ISSUE TITLE
Ability to disable submit button until valid form

### ISSUE THREAD

**Issue by rowej83** [bluebill1049/react-hook-form#77]
**Is your feature request related to a problem? Please describe.**
Currently, can not figure out how to disable/enable the form based on validation rules and the initial formstate.dirty

**Describe the solution you'd like**
A exportable function from useForm that controls the disabled attribute on the submit button

**Comment by bluebill1049** [comment]
can you do something around the `errors` object?

**Comment by bluebill1049** [comment]
hey @rowej83 just a quick follow up, how did you go with it?

**Comment by bluebill1049** [comment]
going to close this, for now, feel free to open it again if you have more questions or feedback :)

**Comment by rowej83** [comment]
Where do you change the mode to on change?

**Comment by bluebill1049** [comment]
When you call the `useForm` :)

https://react-hook-form.com/api/

`useForm({ mode: 'onChnage' });`

**Comment by bluebill1049** [comment]
how did you go?

**Comment by rowej83** [comment]
I changed to onchange mode and tried errors.length on disabled on submit button but it didn't work

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-custom-input-k87mt

**Comment by rowej83** [comment]
that only works if you have one field. type in one of the text box and it'll enable the button while the other 2 inputs are empty. 

https://codesandbox.io/s/react-hook-form-custom-input-4gprv

**Comment by bluebill1049** [comment]
ha, I see, you need to check all fields is touched then, that should fix that issue.

https://react-hook-form.com/api#formState

`touched`

**Comment by rowej83** [comment]
cool, I got it working by checking if the touched array length was the same # of input fields on the form. Thank you :)

**Comment by bluebill1049** [comment]
awesome! going to close the issue now 👍

**Comment by Nelsonfrank** [comment]
Add formState api
```
 const { register, handleSubmit, formState } = useForm({
    mode: "onChange"
  });
```
then in your button 
```
<button disabled={!formState.isValid}/>

``

**Comment by haidi20** [comment]
it's work dud.. thx..

**Comment by haidi20** [comment]
> Add formState api
> 
> ```
>  const { register, handleSubmit, formState } = useForm({
>     mode: "onChange"
>   });
> ```
> 
> then in your button
> 
> ```
> <button disabled={!formState.isValid}/>
> 
> ``
> ```

it's work dud.. thx..

**Comment by CaaioSB** [comment]
> > Add formState api
> > ```
> >  const { register, handleSubmit, formState } = useForm({
> >     mode: "onChange"
> >   });
> > ```
> > 
> > 
> > then in your button
> > ```
> > <button disabled={!formState.isValid}/>
> > 
> > ``
> > ```
> 
> it's work dud.. thx..

This don't work for me, but i have a similar solution.

On API.
```
const { register, handleSubmit,  formState } = useForm({ mode: 'onChange' })
```

On Render.
```
<button disabled={formState.isSubmitting}/>
```

Thank you!

**Comment by minhdongsss** [comment]
> Add formState api
> 
> ```
>  const { register, handleSubmit, formState } = useForm({
>     mode: "onChange"
>   });
> ```
> 
> then in your button
> 
> ```
> <button disabled={!formState.isValid}/>
> 
> ``
> ```

It not work with FormProvider ...

**Comment by bluebill1049** [comment]
> > Add formState api
> > ```
> >  const { register, handleSubmit, formState } = useForm({
> >     mode: "onChange"
> >   });
> > ```
> > 
> > 
> > then in your button
> > ```
> > <button disabled={!formState.isValid}/>
> > 
> > ``
> > ```
> 
> It not work with FormProvider ...

share in a codesandbox.

**Comment by Haraldson** [comment]
How do I go about _actually_ disabling form submission when in certain form states?

Disabling the _button_ doesn't stop the user from submitting the _form_ with the return key in lesser browsers such as Safari.

**Comment by garudamon** [comment]
> Add formState api
> 
> ```
>  const { register, handleSubmit, formState } = useForm({
>     mode: "onChange"
>   });
> ```
> 
> then in your button
> 
> ```
> <button disabled={!formState.isValid}/>
> 
> ``
> ```

thanks you
