### ISSUE TITLE
Form validation does not work without submit button

### ISSUE THREAD

**Issue by pyliakm** [bluebill1049/react-hook-form#79]
I have form which should submit data when all fields are filled without any error and submit button is not needed in this case, but validation does not work without submit button. Can validation work without submit button?
 "version": "3.11.0"

**Comment by bluebill1049** [comment]
yes, you can :)

```
const onSubmit = data => { cosnole.log(data) }

<span onClick={handleSubmit(onSubmit)}>test</span>
```

**Comment by pyliakm** [comment]
Thank you!
