### ISSUE TITLE
Watching a select form does not watch value continuously

### ISSUE THREAD

**Issue by bjeld** [bluebill1049/react-hook-form#80]
...In a form where a user can choose from a dropdown select, and given the option selected, the system needs to "hide/disable" or "show/enable" another form element.

It seems that watching for single fields (in this case, the select element), it only watches the first selection change and not continuously?

**To Reproduce**
go to this sandbox:
https://codesandbox.io/s/react-typescript-yqx5f

**Expected behavior**
the watcher should trigger every time the user changes selection on the dropdown selector so that the system can show/hide the other form element accordingly.

**Comment by bluebill1049** [comment]
@bjeld thanks for report the bug, fixed with 3.11.2

https://codesandbox.io/s/react-typescript-j1qig

**Comment by bjeld** [comment]
well, that was fast :)
Amazing library to work with. Keep up the awesome work
