### ISSUE TITLE
Form element value with type non-string is transformed to string

### ISSUE THREAD

**Issue by pabloibanezcom** [bluebill1049/react-hook-form#82]
When some form element value is not a string (number or bool for instance) returns that value as string handleSubmit. 

I can reproduce this even in the builder (https://react-hook-form.com/builder). Steps to reproduce it: 

- Go to https://react-hook-form.com/builder
- Add one field as number and generate form.
- Fill data in the form (i.e. 7)
- Look at Watch (or Submit after submitting ) and see the value is a string ("7" rather than 7)

**Comment by bluebill1049** [comment]
hey @pabloibanezcom ,

that's actually the standard behavior for all `input`. if you try this in a chrome dev tool, inspect the value of an input. it will be `string`.

**Comment by pabloibanezcom** [comment]
You're right @bluebill1049 . I close the issue.
