### ISSUE TITLE
setError() from submit handler not working

### ISSUE THREAD

**Issue by liketurbo** [bluebill1049/react-hook-form#88]
**Describe the bug**
Basically, if you trying set error with `setError(field, code, msg)` from submit handler you couldn't do that. Common case when server validation fails and you wanna show error accordingly

**To Reproduce**
I got [codesandbox example](https://codesandbox.io/s/ghqh2), if try email `random@example.com` you should get error "Email already taken", but you don't 😔

**Expected behavior**
Appearing error in `errors` object 

**Versions**
 - `react@16.8.3` `react-dom@16.8.3`
 - `react-hook-form@3.11.4`

**Comment by bluebill1049** [comment]
fixed :) thanks heaps for reporting 
https://github.com/bluebill1049/react-hook-form/releases/tag/v3.11.5
