### ISSUE TITLE
[Feature Request] Complex input

### ISSUE THREAD

**Issue by pangpang1987** [bluebill1049/react-hook-form#9]
Consider put in the formatter/mask for the input? And how about the other props for the input like prestine/touched?

**Comment by bluebill1049** [comment]
Yea that should be a good feature to introduce on the next release

**Comment by bluebill1049** [comment]
for isTouched, i think instead of build in side the hook, users can easily just use `errors` object, if errors length is greater than 0, then it is touched. i may just do an example for it. keep api simple. let me know your thoughts.

**Comment by bluebill1049** [comment]
for normalize i have added example: https://codesandbox.io/s/387z7njwzp

should be easy with some javascript onchange event, i have included in the examples folder

**Comment by bluebill1049** [comment]
i guess it keep api simple while leverage what's react already offered you with.

**Comment by bluebill1049** [comment]
working in progress for touch and dirty 

https://github.com/bluebill1049/react-hook-form/tree/feature/dirty-touched

**Comment by bluebill1049** [comment]
version 3 supports https://github.com/bluebill1049/react-hook-form/releases/tag/v3.0.0 `touched` and `dirty`, I am going to close this ticket as masking should be achieved with onChange. Thanks for your feedback.
