### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by burtek** [bluebill1049/react-hook-form#90]
Hi,
First of all - this is GREAT! :D

One question: is there any way of using this with react-native? I assume there isn't any, since it requires `<form onsubmit>` but then again, I tend to be wrong in those cases :D

Thanks, keep up good work!

**Comment by bluebill1049** [comment]
Hey @burtek,

Thank you for your kind words! 

you don't need `form` `onSubmit` to use this hook.

`<span onClick={handleSubmit(ons=Submit)}></span>` will do 

 but currently, I am focusing on the web :( want to get web right first then looking into native :)

cheers
bill

**Comment by burtek** [comment]
Alrighty :D I will then give it a try with an react-native example for ya! :)

**Comment by bluebill1049** [comment]
I am going to close this issue now, will focus on the web first and move towards `react-native` ❤️

**Comment by AkshatGiri** [comment]
@burtek Did you get it to work? I keep getting `Missing field name: [object Object]` warning.

**Comment by bluebill1049** [comment]
hey @AkshatGiri I haven't got chance to look at react-native just yet, but I will do once web version is solid.
