### ISSUE TITLE
Form fail working after reset()

### ISSUE THREAD

**Issue by durianjc** [bluebill1049/react-hook-form#91]
I put sample code here: https://codesandbox.io/s/react-hook-form-get-started-615rp
(It's just copied from your example in official website, but add reset button)

Reproduce:
1 - change values and submit -> work well
2 - reset the form
3 - change values and submit again -> only required fields will be submitted (but the values are old - not changed to what user entered), all other fields are now empty.

After reset() the form, it no longer be able to submit again.

**Comment by durianjc** [comment]
In the form's reset(), I see that it removes everything of the form, including the refs. Why need to do that, I thought reset() is only for reseting the values and errors only?

**Comment by bluebill1049** [comment]
thanks @durianjc  i am looking at it now

**Comment by durianjc** [comment]
Btw, my use case is doing dynamic fields in the form, for example of a filter form where user can add/remove inputs (more/less filters) in the form. I can see that it may have problems with input refs, especially when removing an input. Could it be able to export an "unregister()" function to remove and clean up a input (field) in form? What do you think?

**Comment by bluebill1049** [comment]
hey @durianjc,

this is your problem with reset()

```
<button type="button" onClick={() => reset()}>
  reset
</button>
```

your button didn't have a type, so browser treat it as 'submit', so it's a `submit` with `reset`.

**Comment by bluebill1049** [comment]
when you input gets removed, it should auto unregister :)

**Comment by durianjc** [comment]
> hey @durianjc,
> 
> this is the problem with reset()
> 
> ```
> <button type="button" onClick={() => reset()}>
>   reset
> </button>
> ```
> 
> your button didn't have a type, so browser treat it as 'submit', so it's a `submit` with `reset`.

Hi @bluebill1049, in my project, I call the reset() by code, not by button click and it still has the problem. I modified the code https://codesandbox.io/s/react-hook-form-get-started-615rp to demo again. I added e.preventDefault() to that button, and even move that button outside of the <form />.
![Screenshot at Jun 17 19-16-33](https://user-images.githubusercontent.com/47959733/59603783-81971580-9134-11e9-879a-97bc207fede2.png)

**Comment by bluebill1049** [comment]
how about changing the button type to "button"? and refresh the page, cause it may get cached

```
<button type="button" onClick={() => reset()}>
  reset
</button>
```

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-get-started-l6vjr

**Comment by durianjc** [comment]
Hey, in your above code, I see the only thing that cause it works or not work is this line (not "only" the submit button):

`ref={e => register(e)}` -> works
![Screenshot at Jun 17 19-28-37](https://user-images.githubusercontent.com/47959733/59604434-57deee00-9136-11e9-84cb-c3573d293f94.png)

`ref={register}` -> not work
![Screenshot at Jun 17 19-29-55](https://user-images.githubusercontent.com/47959733/59604440-5f05fc00-9136-11e9-8aac-86c252864508.png)

**Comment by bluebill1049** [comment]
thanks @durianjc you are right. i have patched the issue 

https://codesandbox.io/s/react-hook-form-get-started-l6vjr

**Comment by bluebill1049** [comment]
@durianjc if you are happy with it, I will publish the patch.

**Comment by durianjc** [comment]
YES PLEASE, I just tested and it works as expected. 😍😍😍 THANKS so much for your ultra fast support, love this component!

**Comment by bluebill1049** [comment]
thank you very much for report this issue, next time please send a PR 👍 , would love to see you as a contributor :)

**Comment by bluebill1049** [comment]
https://github.com/bluebill1049/react-hook-form/releases/tag/v3.11.8
