### ISSUE TITLE
Using errors with Typescript results in 

### ISSUE THREAD

**Issue by minhaferzz** [bluebill1049/react-hook-form#93]
**Describe the bug**
Whenever I use the `errors` object, I get this Typescript error:
`Property 'propertyName' does not exist on type 'ErrorMessages<{}>'`

**To Reproduce**
https://codesandbox.io/s/react-typescript-vxzfm

**Expected behavior**
No errors while using the `errors` object.

**Comment by bluebill1049** [comment]
thanks, @minhaferzz strange I don't get it on this demo: https://codesandbox.io/s/o766kp4z05

I will look into why

**Comment by bluebill1049** [comment]
I removed this bit looks fine

`function onSubmit(data: any) {`

https://codesandbox.io/s/react-hook-form-async-submit-validation-pjpbu

**Comment by Graveheart** [comment]
I had the same problem at first, you need to define `validationFields` in order not to get the Typescript errors. Here's a demo:

https://codesandbox.io/s/react-typescript-4phci

**Comment by bluebill1049** [comment]
I see you guys r using `react-script-ts`

```
type inputs = {
  firstName: string,
  lastName: string,
  email: string,
}

function App() {
  const { register, errors, handleSubmit } = useForm<inputs>({
    mode: "onChange"
  });
```

**Comment by bluebill1049** [comment]
I think to define type should resolve this issue, I am going to close this issue for now. feel free to re-open if that still not solve your problem.
