### ISSUE TITLE
Form not being blocked from being sent and error message resets after focusing out of the input

### ISSUE THREAD

**Issue by Romcol** [bluebill1049/react-hook-form#99]
Hi there,

First, thank you for providing us with this tool :) Pardon me if this is not a bug but IMO I find this behavior weird.

I'm trying to check if two password are equals in a form. As I think there is no out of the box solution for this problem I'm using setError to come up with my own comparison (See https://codesandbox.io/s/react-hook-form-seterror-epesl).

The thing is the form is not always blocked from being sent (after one incorrect edit of the second password we are able to send the form). Moreover, sometime clicking outside the incorrect field (under the submit button for example) resets the error message.

I'd like to find a way to do such comparison or at least not to be able to reset the error message with focus out.

Many thanks,

Have a good day!

**Comment by bluebill1049** [comment]
thanks for reporting this bug, i will take a look into that 🙏

**Comment by bluebill1049** [comment]
I have fixed the bug :) thanks for reporting 

https://codesandbox.io/s/react-hook-form-seterror-kylns
will publish it soon. 

I have one suggestion for what you doing here, why not try out `validate` in register

```register({
  validate: value => value === password,
})```

**Comment by bluebill1049** [comment]
https://github.com/bluebill1049/react-hook-form/releases/tag/v3.13.0

**Comment by Romcol** [comment]
Hi, thank you for fixing the bug !!

I don't quite get what native validation has to do with that though :confused: 

Regarding my problematic, we actually need to link onChange to both input, as the form could be filled in reverse order (quick tricky right :laughing:) https://codesandbox.io/s/react-hook-form-seterror-fj6ds?fontsize=14.

Also, we want to display errors only after the form has been submitted, not while the confirm field is being completed, as it will display error to quickly. It would be better if it could be the default behavior (as for other fields). But I guess we can use `formState.submitCount > 0` to check if the form has ever been submitted.

On the other hand, regarding the use of the `validate` rule, it doesn't quite work as expected (see https://codesandbox.io/s/react-hook-form-seterror-vbrup). It keeps displaying errors even when the inputs are correct and doesn't listen to input change.

It would be better if fields comparison would be supported out of the box and without using `setError`. But not sure it would not overwhelm the library.

Anyways, thank you very much for the library and for processing my bug request!

Have a good day!

**Comment by bluebill1049** [comment]
native validation is a separate feature that I have worked for a while which I was going to publish :)

here is a working version with `validate`

https://codesandbox.io/s/react-hook-form-seterror-9dind

`watch` need to be called within the validate due to scope. I will take a look at the other example now.

**Comment by bluebill1049** [comment]
@Romcol happy to close this issue? 🙏

**Comment by Romcol** [comment]
Thanks very much @bluebill1049 ! Only one little use case is not supported by the `validate` when both fields are completed in reverse order, but with setError that should do it (as in sandbox).

**Comment by bluebill1049** [comment]
Awesome! You are so kind and polite. Thank you too!
